### ISSUE TITLE
[Scene Composer] Shadows nowhere to be found

### ISSUE THREAD

**Issue by grizeldi** [jMonkeyEngine/sdk#133]
I don't seem to be able to find an option to enable some form of shadows for the scene composer. I don't seem to be able to find any of the shadow filters on the graphical filter editor list and the renderer versions, which are usually better, are nowhere to be found either.

**Comment by normen** [comment]
Create a new FilterPostProcessor file through "New File", load it and add a shadow filter. Then press the "eye" button in the OpenGL window.

**Comment by grizeldi** [comment]
Shadow filter is not on the filter list.
![screenshot from 2017-07-10 15-23-59](https://user-images.githubusercontent.com/13003371/28020224-d99f65c2-6583-11e7-844c-01616e1568c7.png)

**Comment by grizeldi** [comment]
So I dug into the code and figured out, that there is in fact unfinished code for this already present. It's just not added to the list of actions. I'll dig deeper.

**Comment by grizeldi** [comment]
Commit 4f1e407 added this in. However, like a lot of other filters shadow filter's properties don't appear in the panel on the right, so you can't set the light for the filter. Do we even have a property editor for lights? Or is that on todo like for spatials?

**Comment by grizeldi** [comment]
Also this happens when you try to load a .j3f which has a dlsf attached to it:
```
Could not access constructor of class 'com.jme3.shadow.DirectionalLightShadowFilter'! 
Some types need to have the BinaryImporter set up in a special way. Please doublecheck the setup.
java.lang.InstantiationException: com.jme3.shadow.DirectionalLightShadowFilter
	at java.lang.Class.newInstance(Class.java:427)
	at com.jme3.export.SavableClassUtil.fromName(SavableClassUtil.java:172)
	at com.jme3.export.SavableClassUtil.fromName(SavableClassUtil.java:209)
	at com.jme3.export.binary.BinaryImporter.readObject(BinaryImporter.java:331)
	at com.jme3.export.binary.BinaryInputCapsule.resolveIDs(BinaryInputCapsule.java:483)
	at com.jme3.export.binary.BinaryInputCapsule.readSavableArray(BinaryInputCapsule.java:471)
	at com.jme3.export.binary.BinaryInputCapsule.readSavableArrayList(BinaryInputCapsule.java:587)
	at com.jme3.post.FilterPostProcessor.read(FilterPostProcessor.java:555)
	at com.jme3.export.binary.BinaryImporter.readObject(BinaryImporter.java:342)
	at com.jme3.export.binary.BinaryImporter.load(BinaryImporter.java:242)
	at com.jme3.export.binary.BinaryImporter.load(BinaryImporter.java:125)
	at com.jme3.export.binary.BinaryImporter.load(BinaryImporter.java:109)
	at com.jme3.export.binary.BinaryLoader.load(BinaryLoader.java:36)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at com.jme3.gde.core.assets.AssetDataObject.loadAsset(AssetDataObject.java:191)
	at com.jme3.gde.core.assets.FilterDataObject.loadAsset(FilterDataObject.java:76)
	at com.jme3.gde.core.filters.FilterPostProcessorNode.getFilterPostProcessor(FilterPostProcessorNode.java:94)
	at com.jme3.gde.core.filters.FilterPostProcessorNode$FilterChildren$1.call(FilterPostProcessorNode.java:215)
	at com.jme3.gde.core.filters.FilterPostProcessorNode$FilterChildren$1.call(FilterPostProcessorNode.java:211)
	at com.jme3.app.AppTask.invoke(AppTask.java:142)
	at com.jme3.app.LegacyApplication.runQueuedTasks(LegacyApplication.java:702)
	at com.jme3.app.LegacyApplication.update(LegacyApplication.java:716)
	at com.jme3.gde.core.scene.SceneApplication.update(SceneApplication.java:292)
	at com.jme3.system.awt.AwtPanelsContext.updateInThread(AwtPanelsContext.java:200)
	at com.jme3.system.awt.AwtPanelsContext.access$100(AwtPanelsContext.java:45)
	at com.jme3.system.awt.AwtPanelsContext$AwtPanelsListener.update(AwtPanelsContext.java:69)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.runLoop(LwjglOffscreenBuffer.java:125)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.run(LwjglOffscreenBuffer.java:156)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodException: com.jme3.shadow.DirectionalLightShadowFilter.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 29 more

Aren't filters supposed to be serializable?
```

**Comment by MeFisto94** [comment]
I've just had a look at it and it turns out this is the problem:
https://github.com/MeFisto94/jmonkeyengine/blob/6f90ac55a82b963f7c91f132ec533502f0acb147/jme3-core/src/main/java/com/jme3/shadow/AbstractShadowFilter.java#L62

Every modern Shadow Filter extends that class and hence all parameters are stored in their Renderer Counterparts which aren't inspected by us by default.
