### ISSUE TITLE
File -> Print gives NullPointerException

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/sdk#135]
java.lang.NullPointerException
	at org.netbeans.modules.editor.lib.drawing.DrawEngine.initInfo(DrawEngine.java:227)
	at org.netbeans.modules.editor.lib.drawing.DrawEngine.drawInternal(DrawEngine.java:1194)
	at org.netbeans.modules.editor.lib.drawing.DrawEngine.draw(DrawEngine.java:1103)
	at org.netbeans.modules.editor.lib.drawing.DrawEngine.draw(DrawEngine.java:1070)
	at org.netbeans.editor.BaseDocument.print(BaseDocument.java:1337)
	at org.netbeans.modules.print.editor.Editor.actionPerformed(Editor.java:98)
	at org.netbeans.modules.print.provider.EditorProvider.getIterators(EditorProvider.java:135)
	at org.netbeans.modules.print.provider.EditorProvider.getComponent(EditorProvider.java:104)
	at org.netbeans.modules.print.provider.ComponentProvider.getPages(ComponentProvider.java:79)
	at org.netbeans.modules.print.ui.Preview.createPapers(Preview.java:655)
	at org.netbeans.modules.print.ui.Preview.updated(Preview.java:203)
	at org.netbeans.modules.print.util.UI$Dialog.show(UI.java:689)
	at org.netbeans.modules.print.util.UI$Dialog.show(UI.java:657)
	at org.netbeans.modules.print.ui.Preview.print(Preview.java:141)
	at org.netbeans.modules.print.action.PrintAction.actionPerformed(PrintAction.java:102)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by grizeldi** [comment]
We support printing?? Why?

**Comment by MeFisto94** [comment]
Hm it looks like this is a netbeans bug though, it would be good to know if this is already fixed upstream?

**Comment by MeFisto94** [comment]
https://netbeans.org/bugzilla/show_bug.cgi?id=202230
https://netbeans.org/bugzilla/show_bug.cgi?id=204691
https://netbeans.org/bugzilla/show_bug.cgi?id=238448

So it seems the only way for us would be to submit a pull request to the netbeans repo, however without being familiar with the internal structure, this would be a huge undertaking, given that workarounds are easy (copy and pasting into some editor)

**Comment by grizeldi** [comment]
Just tested, still present.

**Comment by MeFisto94** [comment]
Sure, IF it would change then with NB9.0, but looking at the bugs above, no one seems to care
