### ISSUE TITLE
Bug SceneComposer

### ISSUE THREAD

**Issue by fian46** [jMonkeyEngine/sdk#159]
Step to reproduce : 

1. create a scene, edit it, add something like sphere then save A scene.
2. create another scene B, edit it, link A to B and then save it.
3. edit Scene A do a modification, don't save it just immediately edit B, the scene composer goes blank. 

i am expecting the scene open normally with B scene

**Comment by neph1** [comment]
I get this exception:
```
WARNING [sun.awt.X11.XToolkit]: Exception on Toolkit thread
java.lang.NullPointerException
	at java.desktop/sun.awt.X11.XWindow.handleXCrossingEvent(XWindow.java:936)
	at java.desktop/sun.awt.X11.XComponentPeer.handleXCrossingEvent(XComponentPeer.java:74)
	at java.desktop/sun.awt.X11.XBaseWindow.dispatchEvent(XBaseWindow.java:1150)
	at java.desktop/sun.awt.X11.XBaseWindow.dispatchToWindow(XBaseWindow.java:1108)
	at java.desktop/sun.awt.X11.XToolkit.dispatchEvent(XToolkit.java:621)
[catch] at java.desktop/sun.awt.X11.XToolkit.run(XToolkit.java:736)
	at java.desktop/sun.awt.X11.XToolkit.run(XToolkit.java:652)
	at java.base/java.lang.Thread.run(Thread.java:835)
```
