### ISSUE TITLE
Shader Nodes can't open Lighting.j3md

### ISSUE THREAD

**Issue by erlend-sh** [jMonkeyEngine/sdk#2]
_From @MeFisto94 on February 27, 2016 23:44_

Opening the Lighting.j3md in ShaderNodes leads to a `NullPointerException`.
The Exception itself isn't interesting, but we should find out what goes wrong so that the `ShaderGenerationInfo == null`

See https://github.com/MeFisto94/jmonkeyengine/commit/4b177caa071200b2eb5340e8c5fc20367dbe6537 for where the NPE happens.

_Copied from original issue: jMonkeyEngine/jmonkeyengine#429_

**Comment by erlend-sh** [comment]
_From @Nehon on February 28, 2016 7:3_

Sorry wrong manipulation

**Comment by grizeldi** [comment]
As of right now, I can't even find a shader node version of Lighting.j3md, so I think we can close this.

**Comment by grizeldi** [comment]
Requesting closing of this. Again.

**Comment by MeFisto94** [comment]
It would be good to track down this issue but if someone could come up with a simple example that'd be much easier. for now we wait until we have such a test case.
On the other hand I just opened the Lighting.j3md with the editor (that's possible: go to libraries -> jme3-core and then open the Lighting.j3md), I get:
```
java.lang.IllegalStateException: Cannot instantiate com.jme3.gde.materialdefinition.editor.MatDefEditorlElement
	at org.netbeans.core.spi.multiview.MultiViewFactory$MapMVD.createElement(MultiViewFactory.java:464)
	at org.netbeans.core.multiview.MultiViewModel.getElementForDescription(MultiViewModel.java:222)
	at org.netbeans.core.multiview.MultiViewModel.getActiveElement(MultiViewModel.java:132)
	at org.netbeans.core.multiview.MultiViewModel.getActiveElement(MultiViewModel.java:128)
	at org.netbeans.core.multiview.MultiViewPeer.showCurrentElement(MultiViewPeer.java:470)
	at org.netbeans.core.multiview.MultiViewPeer.showCurrentElement(MultiViewPeer.java:462)
	at org.netbeans.core.multiview.MultiViewPeer$SelectionListener.selectionChanged(MultiViewPeer.java:929)
	at org.netbeans.core.multiview.MultiViewModel.fireSelectionChanged(MultiViewModel.java:259)
	at org.netbeans.core.multiview.MultiViewModel.setActiveDescription(MultiViewModel.java:120)
	at org.netbeans.core.multiview.MultiViewModel$BtnGroup.setSelected(MultiViewModel.java:322)
	at javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:254)
	at javax.swing.ButtonGroup.setSelected(ButtonGroup.java:165)
	at org.netbeans.core.multiview.MultiViewModel$BtnGroup.setSelected(MultiViewModel.java:318)
	at org.netbeans.core.multiview.TabsComponent$ButtonMouseListener.mousePressed(TabsComponent.java:907)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NoSuchMethodException: com.jme3.gde.materialdefinition.editor.MatDefEditorlElement.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.netbeans.core.spi.multiview.MultiViewFactory$MapMVD.createElement(MultiViewFactory.java:450)
	... 47 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.netbeans.core.spi.multiview.MultiViewFactory$MapMVD.createElement(MultiViewFactory.java:447)
	... 47 more
Caused by: java.lang.NullPointerException
	at com.jme3.gde.materialdefinition.editor.MatDefEditorlElement.<init>(MatDefEditorlElement.java:130)
	... 52 more
```
I guess that's simply because Lighting.j3md does not contain any shader node and the editor tries anyway.

**Comment by MeFisto94** [comment]
This fix is not really beautiful: There are 4 Exception Dialogs spawned with the same content as Netbeans tries to invoke the Editor 4 times, but there isn't much we can do about that. At least it's clear to the user what has happened now (instead of searching the logs by launching the sdk from console) and even when not the editor throws an exception giving a vaque hint (MatDefFile could not be loaded).

If one loads a non-shader-node matdef, errors are logged into the SDKs console. If one loads an errorneous shader-node mat def there even is a big yellow warning text (which doesn't work for the others as the editor can't be built without an underlying rough shader node structure (e.g. what Techniques do exist?)

**Comment by MeFisto94** [comment]
Actually this is now a real fun task: Open Lighting.j3md and try to wire the inputs to outputs so everything works for every technique :D
