### ISSUE TITLE
Reinstalling doesn't work on Linux

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#227]
We've had this bug for a while, I thought it's solved, but apparently it's not:
When the SDK is already installed, trying to launch a new installer just crashes without a warning during loading the Wizard Components as it seems.

**Comment by MeFisto94** [comment]
And Uninstalling fails at
```
[2020-01-09 21:37:25.493]: Error during updating wizard UI
[2020-01-09 21:37:25.494]: java.lang.reflect.InvocationTargetException
[2020-01-09 21:37:25.494]:      at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
[2020-01-09 21:37:25.494]:      at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
[2020-01-09 21:37:25.494]:      at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
[2020-01-09 21:37:25.494]:      at org.netbeans.installer.wizard.containers.SwingFrameContainer.updateWizardUi(SwingFrameContainer.java:194)
[2020-01-09 21:37:25.494]:      at org.netbeans.installer.wizard.Wizard.next(Wizard.java:589)
[2020-01-09 21:37:25.494]:      at org.netbeans.installer.wizard.components.WizardSequence.executeForward(WizardSequence.java:67)
[2020-01-09 21:37:25.494]:      at org.mycompany.installer.wizard.components.sequences.MainSequence.executeForward(MainSequence.java:153)
[2020-01-09 21:37:25.494]:      at org.netbeans.installer.wizard.Wizard.next(Wizard.java:595)
[2020-01-09 21:37:25.494]:      at org.netbeans.installer.wizard.components.WizardAction$1.run(WizardAction.java:107)
[2020-01-09 21:37:25.494]: Caused by: java.lang.NullPointerException
[2020-01-09 21:37:25.494]:      at org.mycompany.installer.utils.applications.NetBeansRCPUtils.getApplicationUserDir(NetBeansRCPUtils.java:104)
[2020-01-09 21:37:25.494]:      at org.mycompany.installer.utils.applications.NetBeansRCPUtils.getApplicationUserDirFile(NetBeansRCPUtils.java:70)
[2020-01-09 21:37:25.494]:      at org.mycompany.installer.wizard.components.panels.PreInstallSummaryPanel$PreInstallSummaryPanelSwingUi.initialize(PreInstallSummaryPanel.java:285)
[2020-01-09 21:37:25.494]:      at org.netbeans.installer.wizard.components.WizardComponent$WizardComponentUi.getSwingUi(WizardComponent.java:424)
[2020-01-09 21:37:25.494]:      at org.netbeans.installer.wizard.components.WizardPanel$WizardPanelUi.getSwingUi(WizardPanel.java:147)
[2020-01-09 21:37:25.494]:      at org.netbeans.installer.wizard.components.panels.ErrorMessagePanel$ErrorMessagePanelUi.getSwingUi(ErrorMessagePanel.java:79)
[2020-01-09 21:37:25.494]:      at org.mycompany.installer.wizard.components.panels.PreInstallSummaryPanel$PreInstallSummaryPanelUi.getSwingUi(PreInstallSummaryPanel.java:163)
[2020-01-09 21:37:25.494]:      at org.netbeans.installer.wizard.containers.SwingFrameContainer.updateWizardUi(SwingFrameContainer.java:208)
[2020-01-09 21:37:25.494]:      at org.netbeans.installer.wizard.containers.SwingFrameContainer$1.run(SwingFrameContainer.java:196)
[2020-01-09 21:37:25.494]:      at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
[2020-01-09 21:37:25.494]:      at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
[2020-01-09 21:37:25.494]:      at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
[2020-01-09 21:37:25.494]:      at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
[2020-01-09 21:37:25.494]:      at java.base/java.security.AccessController.doPrivileged(Native Method)
[2020-01-09 21:37:25.495]:      at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[2020-01-09 21:37:25.495]:      at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
[2020-01-09 21:37:25.495]:      at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[2020-01-09 21:37:25.495]:      at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[2020-01-09 21:37:25.495]:      at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[2020-01-09 21:37:25.495]:      at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[2020-01-09 21:37:25.495]:      at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[2020-01-09 21:37:25.495]:      at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by MeFisto94** [comment]
Okay, so with my current installer, the destination dir (installLocation) cannot be chosen freely, but is hardcoded to `~/jmonkeyplatform` and there, the product userdir can be found (` ... product userdir: ${DEFAULT_USERDIR_ROOT}/dev`).

I need to find out why the installation path is set in stone now, maybe it was the update to the nbi engine.

**Comment by MeFisto94** [comment]
Okay, 573dc39a4c18e112465a27ac2fd74677f7072c8e is the commit that removes the Installation Directory choice.

**Comment by MeFisto94** [comment]
Further Investigation has showed that:
The first Panel (`HelloWorldPanel`) is responsible for the Installation Directory and the Shortcuts etc.
The second Panel is actually `ShortcutCreationPanel` from blender and it asks if Shortcuts shall be made for Blender. We just do a bad job with the UI there.

There is a property issue which is why `product.display.name` isn't loaded. I _assume_ this is because the blender products actually are `blender-linux-x64` whereas it tries to load properties for `blender` (which is the products name in the panel), or something.

I'll investigate that and if I find nothing, I'll just "hardcode" the value with the Installer Panel.

**Comment by MeFisto94** [comment]
```
[2020-04-07 20:29:03.531]: Can`t find bundle data using [de_DE] locale and [jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc] classloader
[2020-04-07 20:29:03.531]: java.util.MissingResourceException: Can't find bundle for base name data, locale de_DE
[2020-04-07 20:29:03.531]: 	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
[2020-04-07 20:29:03.531]: 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
[2020-04-07 20:29:03.531]: 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
[2020-04-07 20:29:03.532]: 	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:1284)
[2020-04-07 20:29:03.532]: 	at org.netbeans.installer.utils.ResourceUtils.loadBundle(ResourceUtils.java:184)
[2020-04-07 20:29:03.532]: 	at org.netbeans.installer.utils.ResourceUtils.getBundleMessage(ResourceUtils.java:203)
[2020-04-07 20:29:03.532]: 	at org.netbeans.installer.utils.ResourceUtils.getString(ResourceUtils.java:52)
[2020-04-07 20:29:03.532]: 	at org.netbeans.installer.utils.ResourceUtils.getString(ResourceUtils.java:48)
[2020-04-07 20:29:03.532]: 	at org.mycompany.wizard.panels.ShortcutCreationPanel.<clinit>(ShortcutCreationPanel.java:150)
[2020-04-07 20:29:03.532]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2020-04-07 20:29:03.532]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2020-04-07 20:29:03.532]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2020-04-07 20:29:03.532]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2020-04-07 20:29:03.532]: 	at java.base/java.lang.Class.newInstance(Class.java:584)
[2020-04-07 20:29:03.532]: 	at org.netbeans.installer.wizard.Wizard.loadWizardComponent(Wizard.java:291)
[2020-04-07 20:29:03.532]: 	at org.netbeans.installer.wizard.Wizard.loadWizardComponents(Wizard.java:266)
[2020-04-07 20:29:03.532]: 	at org.netbeans.installer.wizard.Wizard.loadWizardComponents(Wizard.java:219)
[2020-04-07 20:29:03.532]: 	at org.mycompany.ConfigurationLogic.<init>(ConfigurationLogic.java:25)
[2020-04-07 20:29:03.532]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2020-04-07 20:29:03.532]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2020-04-07 20:29:03.532]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2020-04-07 20:29:03.532]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2020-04-07 20:29:03.532]: 	at java.base/java.lang.Class.newInstance(Class.java:584)
[2020-04-07 20:29:03.532]: 	at org.netbeans.installer.product.components.Product.getLogic(Product.java:646)
[2020-04-07 20:29:03.532]: 	at org.netbeans.installer.wizard.components.panels.LicensesPanel.canExecuteForward(LicensesPanel.java:87)
[2020-04-07 20:29:03.532]: 	at org.netbeans.installer.wizard.Wizard.getNext(Wizard.java:878)
[2020-04-07 20:29:03.532]: 	at org.netbeans.installer.wizard.Wizard.next(Wizard.java:578)
[2020-04-07 20:29:03.532]: 	at org.netbeans.installer.wizard.components.WizardSequence.executeForward(WizardSequence.java:67)
[2020-04-07 20:29:03.532]: 	at org.mycompany.installer.wizard.components.sequences.MainSequence.executeForward(MainSequence.java:153)
[2020-04-07 20:29:03.532]: 	at org.netbeans.installer.wizard.Wizard.next(Wizard.java:595)
[2020-04-07 20:29:03.532]: 	at org.netbeans.installer.wizard.components.panels.ErrorMessagePanel$ErrorMessagePanelSwingUi.evaluateNextButtonClick(ErrorMessagePanel.java:174)
[2020-04-07 20:29:03.532]: 	at org.netbeans.installer.wizard.containers.SwingFrameContainer$8.actionPerformed(SwingFrameContainer.java:403)
[2020-04-07 20:29:03.532]: 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
[2020-04-07 20:29:03.532]: 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
[2020-04-07 20:29:03.532]: 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
[2020-04-07 20:29:03.532]: 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[2020-04-07 20:29:03.532]: 	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
[2020-04-07 20:29:03.532]: 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
[2020-04-07 20:29:03.532]: 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
[2020-04-07 20:29:03.532]: 	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
[2020-04-07 20:29:03.532]: 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
[2020-04-07 20:29:03.532]: 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
[2020-04-07 20:29:03.532]: 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
[2020-04-07 20:29:03.532]: 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
[2020-04-07 20:29:03.533]: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[2020-04-07 20:29:03.533]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[2020-04-07 20:29:03.533]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
[2020-04-07 20:29:03.533]: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[2020-04-07 20:29:03.533]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[2020-04-07 20:29:03.533]: 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
That is the relevant stack trace

**Comment by MeFisto94** [comment]
The above comments are rather for #223, sorry.
And since I am now unable to reproduce the crash, I'll close this.
When it happens again, re-open this and/or comment.
Chances are, that the multiple Installer changes have already fixed that though and I was trying to uninstall a half broken build back then.
