### ISSUE TITLE
ShaderNodes: Exception in findConnectionPoint

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#235]
When playing with Shader Nodes, I changed something in `Text` (specifically I changed the MatParam Name and then also connected this to the ColorMult).
Now obviously the UI Part doesn't recognize this change. It should.

If not, it should at least prevent the Exception:
```
java.lang.NullPointerException
	at com.jme3.gde.materialdefinition.editor.MatDefEditorlElement.findConnectPoint(MatDefEditorlElement.java:652)
	at com.jme3.gde.materialdefinition.editor.MatDefEditorlElement.makeConnection(MatDefEditorlElement.java:664)
	at com.jme3.gde.materialdefinition.editor.MatDefEditorlElement.initDiagram(MatDefEditorlElement.java:219)
	at com.jme3.gde.materialdefinition.editor.MatDefEditorlElement.reload(MatDefEditorlElement.java:765)
	at com.jme3.gde.materialdefinition.editor.MatDefEditorlElement.componentShowing(MatDefEditorlElement.java:491)
	at org.netbeans.core.multiview.MultiViewPeer.showCurrentElement(MultiViewPeer.java:480)
	at org.netbeans.core.multiview.MultiViewPeer.showCurrentElement(MultiViewPeer.java:437)
```

**Comment by neph1** [comment]
This is a big issue for the usability of the editor. I'll assign it to myself to keep it at hand.
