### ISSUE TITLE
TestHalfFloat crashed with NoSuchElementException

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/sdk#244]
With current `master` branch:

```
Enter float to convert or 'x' to exit: 
Exception in thread "main" java.util.NoSuchElementException: No line found
	at java.util.Scanner.nextLine(Scanner.java:1540)
	at jme3test.math.TestHalfFloat.main(TestHalfFloat.java:43)
```

**Comment by MeFisto94** [comment]
Probably not much what we can do there when Netbeans Input Wrapper is odd,
maybe Netbeans 11 fixes things
