### ISSUE TITLE
Exception report

### ISSUE THREAD

**Issue by ercomliya** [jMonkeyEngine/sdk#261]
jMonkeyEngine SDK Exception Report
Please submit me to the Issue Tracker
Comment: This means that there was an unexpected exception when parsing the j3md. If this was due to you opening a j3md from a jar (org.openide.filesystems.FSException) then don't report it to us, if it differs, do so!
java.lang.IllegalArgumentException: name
	at sun.misc.URLClassPath$Loader.findResource(URLClassPath.java:703)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:225)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:572)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:570)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(URLClassLoader.java:569)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1096)
	at com.jme3.asset.plugins.ClasspathLocator.locate(ClasspathLocator.java:98)
	at com.jme3.asset.ImplHandler.tryLocate(ImplHandler.java:178)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:359)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:386)
	at com.jme3.gde.materialdefinition.EditableMatDefFile.load(EditableMatDefFile.java:138)
	at com.jme3.gde.materialdefinition.editor.MatDefEditorlElement.<init>(MatDefEditorlElement.java:130)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.netbeans.core.spi.multiview.MultiViewFactory$MapMVD.createElement(MultiViewFactory.java:447)
	at org.netbeans.core.multiview.MultiViewModel.getElementForDescription(MultiViewModel.java:222)
	at org.netbeans.core.multiview.MultiViewModel.getActiveElement(MultiViewModel.java:132)
	at org.netbeans.core.multiview.MultiViewModel.getActiveElement(MultiViewModel.java:128)
	at org.netbeans.core.multiview.MultiViewPeer.privateGetUndoRedo(MultiViewPeer.java:821)
	at org.netbeans.core.multiview.MultiViewPeer.access$700(MultiViewPeer.java:107)
	at org.netbeans.core.multiview.MultiViewPeer$DelegateUndoRedo.removeChangeListener(MultiViewPeer.java:1120)
	at org.openide.actions.UndoRedoAction.run(UndoRedoAction.java:157)
	at org.openide.actions.UndoRedoAction.propertyChange(UndoRedoAction.java:255)
	at org.openide.util.WeakListenerImpl$PropertyChange.propertyChange(WeakListenerImpl.java:215)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at org.netbeans.core.windows.RegistryImpl.doFirePropertyChange(RegistryImpl.java:329)
	at org.netbeans.core.windows.RegistryImpl.access$100(RegistryImpl.java:69)
	at org.netbeans.core.windows.RegistryImpl$1.run(RegistryImpl.java:170)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Operating System: Windows 10
Engine Version as used by the SDK: 3.2-stable

**Comment by MeFisto94** [comment]
So the MatDef Editor fails to load your j3md.
Did you do anything special before this happened?
And did you try to edit a file that is part of a library (jar) instead of having copied it into your Asset Folder?

**Comment by ercomliya** [comment]
in jme3test.texture package
I only try to open UnshadedArray.j3md , than this ecxeption occurs. I didnt change anything. I only wanted report it something doesnt work properly. Thanks for reply

**Comment by MeFisto94** [comment]
How did you get this package? Did you create a new Test Project or did you access this through "Libraries"?

Because we cannot open files outside the `assets` folder, so you need to copy them. The reason is that .jars are more or less read-only.
We should work on an error message, though!
Also does this error happen all the time?

**Comment by ercomliya** [comment]
I created new test project.

**Comment by MeFisto94** [comment]
Yeah, that could very well be, I'll need  to investigate that :)

**Comment by MeFisto94** [comment]
Found the solution. It is confusing in the case of the tests project, so we need to find a solution.
For the general case, there now is #267, for tests we might want to add the source folder as an asset root as well.

The mistake is: Assets must only ever be opened in the special `Project Assets` category under the Project View. Everything else WILL fail.

This is because jme has the habit of putting assets into the assets folder and also because all the other parts are unlikely to be editable (which is why the tests are confusing, there we have all the files in the resource folder of the main project).
