### ISSUE TITLE
Showing HDR Environment is broken

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#266]
```
com.jme3.asset.AssetNotFoundException: Textures/Sky/Path.hdr (Flipped)
    at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:382)
    at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:404)
    at com.jme3.util.SkyFactory.createSky(SkyFactory.java:291)
    at com.jme3.gde.core.scene.SceneApplication$11.run(SceneApplication.java:640)
```

I wonder how this could happen, given that I just added this feature very recently.
The file should stem from testdata.

**Comment by MeFisto94** [comment]
This isn't the case, but:
```java
            Calling pack200(/usr/lib/jvm/java-11-openjdk-amd64/bin/pack200) on /home/marc/Dokumente/02_GIT/sdk/build/installer/nbi_all/ext/infra/build/products/helloworld/build/temp/jmonkeyplatform/libs/jme3-testdata.jar to /home/marc/Dokumente/02_GIT/sdk/build/installer/nbi_all/ext/infra/build/products/helloworld/build/temp/jmonkeyplatform/libs/jme3-testdata.jar.pack.gz
  [package] 
  [package] Warning: The pack200 tool is deprecated, and is planned for removal in a future JDK release.
  [package] 
  [package] OpenJDK 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
  [package] OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
  [package] Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
  [package]     at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
  [package]     at java.base/java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120)
  [package]     at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95)
  [package]     at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:156)
  [package]     at java.base/java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:187)
  [package]     at java.base/com.sun.java.util.jar.pack.Package$File.writeTo(Package.java:845)
  [package]     at java.base/com.sun.java.util.jar.pack.PackageWriter.writeFiles(PackageWriter.java:820)
  [package]     at java.base/com.sun.java.util.jar.pack.PackageWriter.write(PackageWriter.java:76)
  [package]     at java.base/com.sun.java.util.jar.pack.PackerImpl$DoPack.flushPackage(PackerImpl.java:583)
  [package]     at java.base/com.sun.java.util.jar.pack.PackerImpl$DoPack.flushAll(PackerImpl.java:537)
  [package]     at java.base/com.sun.java.util.jar.pack.PackerImpl$DoPack.run(PackerImpl.java:473)
  [package]     at java.base/com.sun.java.util.jar.pack
  [package] .PackerImpl.pack(PackerImpl.java:92)
  [package]     at java.base/com.sun.java.util.jar.pack.Driver.main(Driver.java:322)
  [package] 
  [package] 1
```

happens during Installer Build.

**Comment by grizeldi** [comment]
Most HDRIs are usually pretty big in size, so maybe it runs out of memory when copying it or something?

**Comment by MeFisto94** [comment]
Should be fixed in efd8093, but I guess this shouldn't be the problem because I tried to build it locally. 
I should be part of TestData since a few versions anyway, though...

**Comment by neph1** [comment]
Still happens in main branch. Slightly shifted stacktrace:
```
com.jme3.asset.AssetNotFoundException: Textures/Sky/Path.hdr (Flipped)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:385)
	at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:407)
	at com.jme3.util.SkyFactory.createSky(SkyFactory.java:305)
```

**Comment by tonihele** [comment]
To reproduce, click the toggle skybox button in Scene viewer
![image](https://user-images.githubusercontent.com/8344766/199558040-692b11e6-74e6-4e7e-96a6-b838dc455a9c.png)
