### ISSUE TITLE
Add directionallightshadowfilter or pointlightshadowfilter to the. J3f file. After setting the light name, add it to the code to report an error

### ISSUE THREAD

**Issue by lm165678** [jMonkeyEngine/sdk#273]
Add directionallightshadowfilter or pointlightshadowfilter to the. J3f file. After setting the light name, add it to the code to report an error:
`java.lang.NullPointerException
	at com.jme3.post.Filter.setDepthTexture(Filter.java:304)
	at com.jme3.post.FilterPostProcessor.initFilter(FilterPostProcessor.java:187)
	at com.jme3.post.FilterPostProcessor.reshape(FilterPostProcessor.java:500)
	at com.jme3.post.FilterPostProcessor.initialize(FilterPostProcessor.java:166)
	at com.jme3.renderer.RenderManager.notifyReshape(RenderManager.java:311)
	at com.jme3.renderer.RenderManager.notifyReshape(RenderManager.java:336)
	at com.jme3.app.LegacyApplication.reshape(LegacyApplication.java:543)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:194)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by lm165678** [comment]
Can SDK provide adding custom filters just like adding custom controllers.

**Comment by MeFisto94** [comment]
Can you provide more info on what has happened? Judging by the stacktrace this happens when you create a filter, save it to a file and load it into your game?
