### ISSUE TITLE
Unable to open jmonkeyengine 3.3.0 from zip on WIndows x64

### ISSUE THREAD

**Issue by chalcosoma** [jMonkeyEngine/sdk#298]
Hello! I downloaded the jmonkeyengine 3.3.0 zip file, extracted it and I tried to run it. So, the splash screen is shown and load until "turning on modules..." and then it shows the following error (I opened it in the Command Prompt):

```
mai. 13, 2021 8:19:14 PM org.netbeans.ProxyURLStreamHandlerFactory register
SEVERE: No way to find original stream handler for jar protocol
java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.net.URLStreamHandler java.net.URL.handler accessible: module java.base does not "opens java.net" to unnamed module @7699a589
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
        at org.netbeans.ProxyURLStreamHandlerFactory.register(ProxyURLStreamHandlerFactory.java:59)
        at org.netbeans.JarClassLoader.<clinit>(JarClassLoader.java:117)
        at org.netbeans.MainImpl.execute(MainImpl.java:153)
        at org.netbeans.MainImpl.main(MainImpl.java:60)
        at org.netbeans.Main.main(Main.java:58)

java.lang.Error: factory already defined
        at java.base/java.net.URL.setURLStreamHandlerFactory(URL.java:1259)
        at org.eclipse.osgi.framework.internal.core.Framework.installURLStreamHandlerFactory(Framework.java:1765)
        at org.eclipse.osgi.framework.internal.core.Framework.<init>(Framework.java:232)
        at org.eclipse.osgi.framework.internal.core.EquinoxLauncher.internalInit(EquinoxLauncher.java:67)
        at org.eclipse.osgi.framework.internal.core.EquinoxLauncher.init(EquinoxLauncher.java:37)
        at org.eclipse.osgi.launch.Equinox.init(Equinox.java:178)
        at org.netbeans.modules.netbinox.Netbinox.init(Netbinox.java:63)
        at org.netbeans.core.netigso.Netigso.prepare(Netigso.java:145)
        at org.netbeans.NetigsoHandle.turnOn(NetigsoHandle.java:115)
        at org.netbeans.ModuleManager.enable(ModuleManager.java:1437)
        at org.netbeans.ModuleManager.enable(ModuleManager.java:1254)
        at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:315)
        at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:251)
        at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:298)
        at org.netbeans.core.startup.Main.getModuleSystem(Main.java:156)
        at org.netbeans.core.startup.Main.getModuleSystem(Main.java:125)
        at org.netbeans.core.startup.Main.start(Main.java:282)
        at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

My specs:
Intel Core i5-2500K CPU
Edition	Windows 10 Pro
Version	20H2
OS build	19042.985
GeForce GTX 1050 Ti Driver: 466.27

**Comment by MeFisto94** [comment]
When you use the zip, it's the platform independant variant, which does not come with a JVM.
My guess is you use a too new jvm, where reflection access is finally restricted and our netbeans isn't prepared yet.
Would you tell me the jvm version you're running?

Besides you can always launch the SDK with an older JVM Version and the game with a more recent (provided it can already compile for those, maven and gradle are kind of bleeding edge for java 16, e.g.), I think we bundle Java 11 by default

**Comment by chalcosoma** [comment]
Thank you. I'm using OpenJDK 16. What version should I use?

**Comment by chalcosoma** [comment]
I installed AdoptOpenJDK 14 and the problem is solved. Thank you.

**Comment by MeFisto94** [comment]
Yeah, sorry for the late reply, everything below 16 should be okay, 11.0.6 is what the installer uses/brings.

I guess this issue will be fixed when netbeans downloads/releases Version ~16, currently the latest is 12.3 (though I don't know if the versions line up with the expected jvm versions anymore)

**Comment by tonihele** [comment]
They have changed the release schedule to better accommodate to Java 17 LTS. Soon they'll release Netbeans 12.4 which adds support for Java 16. Followed by NB 12.5 and 12.6. One of which adds some sort of support for Java 17. 

February 2022, they'll release Netbeans 13 LTS which is then guaranteed to support Java 17 etc. 

A bit tricky for the SDK. Basically we release so rarely that we could and maybe should stick to NB LTS releases. But that also means that there will be a big gap for the SDK that it only supports Java up to 14 (?).
