### ISSUE TITLE
NPE when adding node MatParam without name in Shader Editor

### ISSUE THREAD

**Issue by neph1** [jMonkeyEngine/sdk#325]
java.lang.NullPointerException
	at com.jme3.gde.core.editor.nodes.NodePanel.cleanup(NodePanel.java:212)
	at com.jme3.gde.core.editor.nodes.Diagram.removeNode(Diagram.java:270)
	at com.jme3.gde.core.editor.nodes.Diagram.removeSelected(Diagram.java:245)
	at com.jme3.gde.core.editor.nodes.NodePanel.delete(NodePanel.java:371)
	at com.jme3.gde.materialdefinition.editor.ShaderNodeToolBar.deleteButtonActionPerformed(ShaderNodeToolBar.java:125)
	at com.jme3.gde.materialdefinition.editor.ShaderNodeToolBar$2.actionPerformed(ShaderNodeToolBar.java:114)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)

**Comment by MeFisto94** [comment]
Regarding the commit: I didn't check too much logic, maybe something else is borked if the toolbar has no parent, but we will find that out later, it should have other side effects as well.
I just checked for null for now, because I assume the toolbar just isn't fully constructed or something
