### ISSUE TITLE
Empy Scene (.j3o) not working

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#33]
See http://hub.jmonkeyengine.org/t/jmonkeyengine-3-1-alpha-3-released/35328/9
Either it's because we are writing an incomplete file or because the BinaryInputCapsule just can't handle empty files.

**Comment by MeFisto94** [comment]
So it turns out that this action is simply taking the file from jme3-scenecomposer/src/.../Scene.j3o
The Investigation shows that the crash occurs when trying to read the Scale:

`scale.set((Vector3f)capsule.readSavable("scale", Vector3f.UNIT_XYZ));`
Does anyone know if this Scene.j3o could still be a 3.0 thing which is broken now?

Anyhow this shouldn't lead to such an issue, I'd say?
`cObj.aliasFields.get(alias).type;` one of those is null.

**Comment by Dokthar** [comment]
There are no problems opening the Scene.j3o (from the sdk sources, copied & pasted) The problem seem to happen at the creation of the new file, few bytes are different .

**Comment by Dokthar** [comment]
this problem already occurs at : 
50c9d4200283f7576f7bf72622903c16d68fd87c
3c32355c3508a34ae6f538d4cfc1d5c40e9ed7e2

**Comment by MeFisto94** [comment]
It doesn't here: https://github.com/jMonkeyEngine/jmonkeyengine/commit/f4098ce89cc65b381906cf3859d17281b264c313
That's before the split and all but it's only 15 days ago, so it might be NB8.1 breaking.

Normen suggested this:
>j3o is the only binary file we add, maybe thats the issue? Maybe theres some new flag for binary files? Text files don't have the issue I suppose?
You could try fpp files, that should be a binary as well
If they're broken too then its probably a NB issue
"New Filter" and then try to open it on a scene

Doing that I noticed something different:
You actually CAN add filters (so they are displayed in SceneComposer), but you cannot see them in the FilterExplorer. Probably because of the change you did?

```
java.lang.NullPointerException
	at com.jme3.gde.core.filters.impl.JmeFilter.getExplorerObjectClass(JmeFilter.java:79)
	at com.jme3.gde.core.filters.FilterPostProcessorNode$FilterChildren.createNodes(FilterPostProcessorNode.java:238)
	at org.openide.nodes.Children$Keys$KE.nodes(Children.java:1679)
[catch] at org.openide.nodes.ChildrenArray.nodesFor(ChildrenArray.java:149)
	at org.openide.nodes.EntrySupportDefault$Info.nodes(EntrySupportDefault.java:805)
	at org.openide.nodes.EntrySupportDefault.updateAdd(EntrySupportDefault.java:441)
	at org.openide.nodes.EntrySupportDefault.setEntries(EntrySupportDefault.java:295)
	at org.openide.nodes.EntrySupport.setEntries(EntrySupport.java:83)
	at org.openide.nodes.Children$Keys$2.run(Children.java:1573)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation$1Exec.run(DefaultMutexImplementation.java:1016)
	at org.openide.nodes.Children$ProjectManagerDeadlockDetector.execute(Children.java:1938)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.postRequest(DefaultMutexImplementation.java:1022)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.postRequest(DefaultMutexImplementation.java:985)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.postWriteRequest(DefaultMutexImplementation.java:356)
	at org.openide.util.Mutex.postWriteRequest(Mutex.java:388)
	at org.openide.nodes.Children$Keys.applyKeys(Children.java:1582)
	at org.openide.nodes.Children$Keys.setKeys(Children.java:1526)
	at com.jme3.gde.core.filters.FilterPostProcessorNode$FilterChildren.addNotify(FilterPostProcessorNode.java:198)
	at com.jme3.gde.core.filters.FilterPostProcessorNode$2.run(FilterPostProcessorNode.java:127)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
```

**Comment by MeFisto94** [comment]
Found another hint!
http://www.fileformat.info/info/unicode/char/0fffd/index.htm
-> Netbeans replaces some non-UTF-8 chars with `0xEF 0xBF 0xBD (efbfbd)` since that's the Sequence for the linked Replacement Character (We it's unable to convert the input byte)

**Comment by Dokthar** [comment]
good job @MeFisto94  looks nice.
