### ISSUE TITLE
Gradle template gives out stack trace to logs

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/sdk#363]
When opening the project wizard we get a INFO stacktrace. This causes no harm I suppose. But probably very trivial to fix too.

```
INFO [org.netbeans.core.startup.layers.BinaryFS]: value = com.jme3.gde.templates.Bundle#Templates/Project/JME3/GradleDesktopGameProject.zip from Templates/Project/JME3/Basic Gradle Game
java.util.MissingResourceException: Can't find resource for bundle org.openide.util.NbBundle$PBundle, key Templates/Project/JME3/GradleDesktopGameProject.zip
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
[catch] at org.netbeans.core.startup.layers.BinaryFS$AttrImpl.getValue(BinaryFS.java:676)
	at org.netbeans.core.startup.layers.BinaryFS$BFSBase.getAttribute(BinaryFS.java:506)
	at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:918)
	at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:851)
	at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:914)
	at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:851)
	at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:772)
	at org.netbeans.modules.openide.filesystems.FileSystemStatus.annotateName(FileSystemStatus.java:83)
	at org.netbeans.modules.openide.filesystems.FileSystemStatus.annotateName(FileSystemStatus.java:58)
	at org.openide.loaders.DataNode.getDisplayName(DataNode.java:169)
	at org.openide.nodes.FilterNode.getDisplayName(FilterNode.java:503)
	at org.openide.explorer.view.VisualizerNode.getDisplayName(VisualizerNode.java:203)
	at org.openide.explorer.view.NodeRenderer.getListCellRendererComponent(NodeRenderer.java:166)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1439)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.locationToIndex(BasicListUI.java:1004)
	at java.desktop/javax.swing.JList.locationToIndex(JList.java:1600)
	at org.openide.explorer.view.ListView$NbList.access$1301(ListView.java:783)
	at org.openide.explorer.view.ListView$NbList$GuardedActions.run(ListView.java:893)
	at org.openide.explorer.view.ListView$NbList$GuardedActions.<init>(ListView.java:863)
	at org.openide.explorer.view.ListView$NbList.locationToIndex(ListView.java:933)
	at java.desktop/javax.swing.JList.getFirstVisibleIndex(JList.java:1044)
	at org.openide.explorer.view.ListView.updateSelectionImpl(ListView.java:703)
	at org.openide.explorer.view.ListView.access$500(ListView.java:114)
	at org.openide.explorer.view.ListView$GuardedActions.run(ListView.java:520)
	at org.openide.explorer.view.ListView$GuardedActions.<init>(ListView.java:497)
	at org.openide.explorer.view.ListView.updateSelection(ListView.java:693)
	at org.openide.explorer.view.ListView.access$2000(ListView.java:114)
	at org.openide.explorer.view.ListView$Listener.intervalAdded(ListView.java:1373)
	at java.desktop/javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:153)
	at org.openide.explorer.view.NodeListModel.added(NodeListModel.java:350)
	at org.openide.explorer.view.NodeListModel$Listener.added(NodeListModel.java:429)
	at org.openide.explorer.view.VisualizerChildren.added(VisualizerChildren.java:223)
	at org.openide.explorer.view.VisualizerEvent$Added.run(VisualizerEvent.java:85)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:172)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation$1R.run(DefaultMutexImplementation.java:1016)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.doWrapperAccess(DefaultMutexImplementation.java:1033)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:162)
	at org.openide.util.Mutex.readAccess(Mutex.java:241)
	at org.openide.explorer.view.VisualizerNode$QP.processQueue(VisualizerNode.java:660)
	at org.openide.explorer.view.VisualizerNode$QP.runSafe(VisualizerNode.java:639)
	at org.openide.explorer.view.VisualizerNode.childrenAdded(VisualizerNode.java:335)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openide.util.WeakListenerImpl$ProxyListener.invoke(WeakListenerImpl.java:462)
	at com.sun.proxy.$Proxy14.childrenAdded(Unknown Source)
	at org.openide.nodes.Node.fireSubNodesChange(Node.java:1121)
	at org.openide.nodes.EntrySupportDefault.notifyAdd(EntrySupportDefault.java:579)
	at org.openide.nodes.EntrySupportDefault.updateAdd(EntrySupportDefault.java:429)
	at org.openide.nodes.EntrySupportDefault.setEntries(EntrySupportDefault.java:272)
	at org.openide.nodes.EntrySupport.setEntries(EntrySupport.java:60)
	at org.openide.nodes.Children$Keys$2.run(Children.java:1548)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.leaveImpl(DefaultMutexImplementation.java:617)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.leave(DefaultMutexImplementation.java:550)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:174)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation$1R.run(DefaultMutexImplementation.java:1016)
	at org.openide.nodes.Children$ProjectManagerDeadlockDetector.execute(Children.java:1914)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.doWrapperAccess(DefaultMutexImplementation.java:1035)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:162)
	at org.openide.util.Mutex.readAccess(Mutex.java:241)
	at org.openide.explorer.ExplorerManager.setRootContext(ExplorerManager.java:498)
	at org.netbeans.modules.project.ui.TemplatesPanelGUI$ExplorerProviderPanel.setRootNode(TemplatesPanelGUI.java:516)
	at org.netbeans.modules.project.ui.TemplatesPanelGUI.propertyChange(TemplatesPanelGUI.java:294)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8731)
	at org.netbeans.modules.project.ui.TemplatesPanelGUI$ExplorerProviderPanel.access$900(TemplatesPanelGUI.java:504)
	at org.netbeans.modules.project.ui.TemplatesPanelGUI$ExplorerProviderPanel$2.run(TemplatesPanelGUI.java:587)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at org.netbeans.core.windows.services.NbPresenter.superShow(NbPresenter.java:1074)
	at org.netbeans.core.windows.services.NbPresenter.doShow(NbPresenter.java:1124)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:1096)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:106)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:123)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:77)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:71)
	at org.openide.util.Mutex.readAccess(Mutex.java:199)
	at org.netbeans.core.windows.services.NbPresenter.show(NbPresenter.java:1081)
	at java.desktop/java.awt.Component.show(Component.java:1716)
	at java.desktop/java.awt.Component.setVisible(Component.java:1663)
	at java.desktop/java.awt.Window.setVisible(Window.java:1031)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.netbeans.core.windows.services.DialogDisplayerImpl$AWTQuery.showDialog(DialogDisplayerImpl.java:281)
	at org.netbeans.core.windows.services.DialogDisplayerImpl$AWTQuery.run(DialogDisplayerImpl.java:175)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
CONFIG [null]: Missing resource from class: org.openide.util.NbBundle$PBundle
CONFIG [null]: Key which was not found: Templates/Project/JME3/GradleDesktopGameProject.zip
```

**Comment by tonihele** [comment]
Still an issue with the new Wizard:
```
java.util.MissingResourceException: Can't find resource for bundle org.openide.util.NbBundle$PBundle, key Templates/Project/JME3/GradleDesktopGameProject.zip
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
[catch] at org.netbeans.core.startup.layers.BinaryFS$AttrImpl.getValue(BinaryFS.java:676)
	at org.netbeans.core.startup.layers.BinaryFS$BFSBase.getAttribute(BinaryFS.java:506)
	at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:918)
	at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:851)
	at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:914)
	at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:851)
	at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:772)
	at org.netbeans.modules.openide.filesystems.FileSystemStatus.annotateName(FileSystemStatus.java:83)
	at org.netbeans.modules.openide.filesystems.FileSystemStatus.annotateName(FileSystemStatus.java:58)
	at org.openide.loaders.DataNode.getDisplayName(DataNode.java:169)
	at org.openide.nodes.FilterNode.getDisplayName(FilterNode.java:503)
	at org.openide.explorer.view.VisualizerNode.getDisplayName(VisualizerNode.java:203)
	at org.openide.explorer.view.NodeRenderer.getListCellRendererComponent(NodeRenderer.java:166)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1439)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:648)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1680)
	at org.openide.explorer.view.ListView$NbList.access$1101(ListView.java:783)
	at org.openide.explorer.view.ListView$NbList$GuardedActions.run(ListView.java:887)
	at org.openide.explorer.view.ListView$NbList$GuardedActions.<init>(ListView.java:863)
	at org.openide.explorer.view.ListView$NbList.getPreferredSize(ListView.java:923)
	at java.desktop/javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:795)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at org.openide.explorer.view.ListView.access$201(ListView.java:114)
	at org.openide.explorer.view.ListView$GuardedActions.run(ListView.java:512)
	at org.openide.explorer.view.ListView$GuardedActions.<init>(ListView.java:497)
	at org.openide.explorer.view.ListView.doLayout(ListView.java:547)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at org.openide.explorer.view.ListView.access$101(ListView.java:114)
	at org.openide.explorer.view.ListView$GuardedActions.run(ListView.java:509)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:188)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation$1R.run(DefaultMutexImplementation.java:1014)
	at org.openide.nodes.Children$ProjectManagerDeadlockDetector.execute(Children.java:1914)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.doWrapperAccess(DefaultMutexImplementation.java:1035)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:181)
	at org.openide.util.Mutex.readAccess(Mutex.java:199)
	at org.openide.explorer.view.ListView$GuardedActions.<init>(ListView.java:499)
	at org.openide.explorer.view.ListView.validateTree(ListView.java:537)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:745)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:742)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1889)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at org.netbeans.core.windows.services.NbPresenter.superShow(NbPresenter.java:1074)
	at org.netbeans.core.windows.services.NbPresenter.doShow(NbPresenter.java:1124)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:1096)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:106)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:123)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:77)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:71)
	at org.openide.util.Mutex.readAccess(Mutex.java:199)
	at org.netbeans.core.windows.services.NbPresenter.show(NbPresenter.java:1081)
	at java.desktop/java.awt.Component.show(Component.java:1716)
	at java.desktop/java.awt.Component.setVisible(Component.java:1663)
	at java.desktop/java.awt.Window.setVisible(Window.java:1031)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.netbeans.core.windows.services.DialogDisplayerImpl$AWTQuery.showDialog(DialogDisplayerImpl.java:281)
	at org.netbeans.core.windows.services.DialogDisplayerImpl$AWTQuery.run(DialogDisplayerImpl.java:175)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
CONFIG [null]: Missing resource from class: org.openide.util.NbBundle$PBundle
CONFIG [null]: Key which was not found: Templates/Project/JME3/GradleDesktopGameProject.zip
```
