### ISSUE TITLE
NPE when selecting "All data" when updating mesh that has no animation data

### ISSUE THREAD

**Issue by neph1** [jMonkeyEngine/sdk#412]
If you have a gltf model which you update and the ExternalChangeScanner prompts if you want to update that mesh, and you select "All data", but the model doesn't have animation data, it will still try to do something which yields an NPE.

```
java.lang.NullPointerException
	at com.jme3.gde.core.util.SpatialUtil.hasAnimations(SpatialUtil.java:128)
	at com.jme3.gde.core.assets.ExternalChangeScanner.applyExternalData(ExternalChangeScanner.java:163)
	at com.jme3.gde.core.assets.ExternalChangeScanner.lambda$notifyUser$0(ExternalChangeScanner.java:140)
	at com.jme3.app.AppTask.invoke(AppTask.java:147)
```

**Comment by neph1** [comment]
False alarm it seems. I had converted with one version of the sdk and it wasn't appreciated by the other. Hash issue?
