### ISSUE TITLE
Bug 257245 - Formatting and template exception in editor : NullPointerException at java.lang.String.contentEquals 

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/sdk#42]
this exception happened to me recently with SDK Netbeans 8.1  
Using netbeans editor auto code complete with "Ctrl" + "Space" .
 Example : `spatial.setLocalTranslation(0, 0, 0);`
```
java.lang.NullPointerException
    at java.lang.String.contentEquals(String.java:1066)
    at org.netbeans.modules.java.source.save.Reformatter$Pretty.blankLines(Reformatter.java:3532)
    at org.netbeans.modules.java.source.save.Reformatter$Pretty.newline(Reformatter.java:3280)
    at org.netbeans.modules.java.source.save.Reformatter$Pretty.visitBlock(Reformatter.java:1556)
    at org.netbeans.modules.java.source.save.Reformatter$Pretty.visitBlock(Reformatter.java:406)
    at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:924)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
    at org.netbeans.modules.java.source.save.Reformatter$Pretty.reformat(Reformatter.java:523)
    at org.netbeans.modules.java.source.save.Reformatter.reformatImpl(Reformatter.java:239)
    at org.netbeans.modules.java.source.save.Reformatter.reformat(Reformatter.java:109)
    at org.netbeans.modules.editor.indent.TaskHandler$MimeItem.runTask(TaskHandler.java:557)
    at org.netbeans.modules.editor.indent.TaskHandler.runTasks(TaskHandler.java:316)
    at org.netbeans.modules.editor.indent.IndentImpl.reformat(IndentImpl.java:365)
    at org.netbeans.modules.editor.indent.api.Reformat.reformat(Reformat.java:154)
    at org.netbeans.lib.editor.codetemplates.CodeTemplateInsertHandler.run(CodeTemplateInsertHandler.java:371)
    at org.netbeans.editor.GuardedDocument.runAtomicAsUser(GuardedDocument.java:356)
    at org.netbeans.lib.editor.codetemplates.CodeTemplateInsertHandler.insertTemplate(CodeTemplateInsertHandler.java:284)
    at org.netbeans.lib.editor.codetemplates.CodeTemplateInsertHandler.processTemplate(CodeTemplateInsertHandler.java:252)
    at org.netbeans.lib.editor.codetemplates.CodeTemplateManagerOperation.insert(CodeTemplateManagerOperation.java:298)
    at org.netbeans.lib.editor.codetemplates.api.CodeTemplate.insert(CodeTemplate.java:107)
    at org.netbeans.modules.editor.java.JavaCompletionItem.process(JavaCompletionItem.java:580)
    at org.netbeans.modules.editor.java.JavaCompletionItem.defaultAction(JavaCompletionItem.java:300)
    at org.netbeans.modules.editor.completion.CompletionImpl.dispatchKeyEvent(CompletionImpl.java:676)
    at org.netbeans.modules.editor.completion.CompletionImpl.keyPressed(CompletionImpl.java:404)
    at java.awt.AWTEventMulticaster.keyPressed(AWTEventMulticaster.java:250)
    at java.awt.AWTEventMulticaster.keyPressed(AWTEventMulticaster.java:249)
    at java.awt.Component.processKeyEvent(Component.java:6493)
    at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
    at java.awt.Component.processEvent(Component.java:6312)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
    at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
    at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
    at java.awt.Component.dispatchEventImpl(Component.java:4762)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

It was fixed in build 201603150001 (it is nightly) : https://netbeans.org/bugzilla/show_bug.cgi?id=257245 

I found this zip : 
http://bits.netbeans.org/dev/nightly/2016-03-25_00-01-48/zip/
Is it possible to change current SDK netbeans build in `gradle.properties`: 
`netbeansUrl = http://download.netbeans.org/netbeans/8.1/final/zip/netbeans-8.1-201510222201-javase.zip`

to this : 
`http://bits.netbeans.org/dev/nightly/2016-03-25_00-01-48/zip/netbeans-trunk-nightly-201603250001-javase.zip`

**Comment by MeFisto94** [comment]
Hey,
Sorry for the late reply. We actually talked about this internally but I forgot to reply to this Issue.

As far as this goes you are the first one to have that issue at all and whilst this indeed is/was a bug, we've decided that we wont update to the latest nightly.

The thing is updating to 8.1 is what led us to those bugs, so relying on a nightly is even worse^^ 
You however are free to compile your SDK against nightly and I've seen that you did great support on the forums, so you might link this issue to others experiencing this issue :) 

I've seen that Netbeans had ~200 bugixes as 8.1-patch1 released on 18th Feburary so we might see something comparable as patch2 in some weeks/months. This would allow you to download the bugfix through the netbeans internal system (and us having those fixes included)

**Comment by Ali-RS** [comment]
Thanks @MeFisto94. No problem, I may try to compile source myself and will test if it works correctly or no. If that works OK, i will post in forum. 
And that internal update system seems cool. Thanks

**Comment by Ali-RS** [comment]
And I did compile code with this nightly netbeans source:` netbeansUrl = http://bits.netbeans.org/download/trunk/nightly/latest/zip/netbeans-trunk-nightly-201603290001-javase.zip`
and it did fix the problem. 
Will play with that for a few days and if no problem occurs I may post it on the forum for anyone who may run to this issue.
Thanks
