### ISSUE TITLE
Scene can't be saved

### ISSUE THREAD

**Issue by EngjellRraklli** [jMonkeyEngine/sdk#47]
After making changes to a new scene, it can't be saved. If closing and click yes in the confirmation popup, the scene can't be opened anymore.S.D.K problem with the latest alpha version.

**Comment by MeFisto94** [comment]
Could you upload us such a scene so we can analyse where the problem is?
What changes did you do to the file? Motion Events aren't supported there due to the underlying engine version

**Comment by EngjellRraklli** [comment]
Basically I add a terrain and afterwards the scene can't be saved anymore. If I close it and confirm the popup in order to save it, it seems as it goes through, however the scene can't be opened anymore with the error message "Error opening {scene name}". Please find attached the scene sample so you can analyse it.

[Scenes.zip](https://github.com/jMonkeyEngine/sdk/files/200855/Scenes.zip)

**Comment by MeFisto94** [comment]
I have looked into it, it's related to the latest cloning changes.
Feel free to use the older versions (3.1-alpha2, or maybe even 3.1-alpha3-SNAPSHOT)

```
java.lang.NullPointerException
	at com.jme3.util.clone.Cloner.javaClone(Cloner.java:357)
	at com.jme3.terrain.geomipmap.TerrainLodControl.cloneFields(TerrainLodControl.java:323)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:255)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.util.clone.ListCloneFunction.cloneFields(ListCloneFunction.java:66)
	at com.jme3.util.clone.ListCloneFunction.cloneFields(ListCloneFunction.java:43)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:228)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.scene.Spatial.cloneFields(Spatial.java:1422)
	at com.jme3.scene.Node.cloneFields(Node.java:726)
	at com.jme3.terrain.geomipmap.TerrainQuad.cloneFields(TerrainQuad.java:1816)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:255)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.util.clone.ListCloneFunction.cloneFields(ListCloneFunction.java:66)
	at com.jme3.util.clone.ListCloneFunction.cloneFields(ListCloneFunction.java:43)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:228)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.scene.Node.cloneFields(Node.java:728)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:255)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.scene.Spatial.clone(Spatial.java:1289)
	at com.jme3.scene.Node.clone(Node.java:684)
	at com.jme3.scene.Node.clone(Node.java:62)
	at com.jme3.scene.Spatial.clone(Spatial.java:1368)
	at com.jme3.scene.Spatial.clone(Spatial.java:69)
	at com.jme3.asset.CloneableAssetProcessor.createClone(CloneableAssetProcessor.java:48)
	at com.jme3.asset.DesktopAssetManager.registerAndCloneSmartAsset(DesktopAssetManager.java:320)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:382)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:419)
[catch] at com.jme3.gde.core.assets.SpatialAssetDataObject.loadAsset(SpatialAssetDataObject.java:95)
	at com.jme3.gde.scenecomposer.OpenSceneComposer$1.run(OpenSceneComposer.java:37)
	at java.lang.Thread.run(Thread.java:745)
```

I have to change it so that the Exceptions are shown inside the SDK (Even when you don't run it in your debuger)

**Comment by MeFisto94** [comment]
See [#466](https://github.com/jMonkeyEngine/jmonkeyengine/issues/466) for the progress on your bug (it's a bug in the engine itself rather than the SDK. The j3o would be broken if you'd load it in your game)
