### ISSUE TITLE
Asset listening errors on log

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/sdk#472]
I just have this Ant project, basic game open and it seems to produce some errors on the log:

```
java.lang.AssertionError: Already listening to [C:\Users\Toni\Documents\ToniArts\BasicGame2\build\classes@15c79722:72b59398] now requested for C:\Users\Toni\Documents\ToniArts\BasicGame2\build\classes@15c79722:72b59398
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.listenToAll(FileObjectKeeper.java:198)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.addRecursiveListener(FileObjectKeeper.java:82)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.addRecursiveListener(FolderObj.java:657)
	at com.jme3.gde.core.assets.ProjectAssetManager.loadClassLoader(ProjectAssetManager.java:180)
	at com.jme3.gde.core.assets.ProjectAssetManager$3.run(ProjectAssetManager.java:293)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.postRequest(DefaultMutexImplementation.java:975)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.postWriteRequest(DefaultMutexImplementation.java:292)
	at org.openide.util.Mutex.postWriteRequest(Mutex.java:369)
	at com.jme3.gde.core.assets.ProjectAssetManager.updateClassLoader(ProjectAssetManager.java:289)
	at com.jme3.gde.core.assets.ProjectAssetManager$2.propertyChange(ProjectAssetManager.java:279)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at org.netbeans.api.java.classpath.ClassPath.firePropertyChange(ClassPath.java:691)
	at org.netbeans.api.java.classpath.ClassPath$RootsListener.processEvent(ClassPath.java:1436)
	at org.netbeans.api.java.classpath.ClassPath$RootsListener.fileDataCreated(ClassPath.java:1413)
	at org.openide.filesystems.FileChangeImpl.fileDataCreated(FileChangeImpl.java:140)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEventImpl(FCLSupport.java:147)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapperSingle.dispatchAllEventsSync(FCLSupport.java:199)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEvent(FCLSupport.java:112)
	at org.openide.filesystems.FCLSupport.dispatchEvent(FCLSupport.java:80)
	at org.openide.filesystems.FileObject$ED.dispatch(FileObject.java:1416)
	at org.openide.filesystems.FileSystem$EventDispatcher.run(FileSystem.java:770)
	at org.openide.filesystems.EventControl.dispatchEvent(EventControl.java:59)
	at org.openide.filesystems.FileSystem.dispatchEvent(FileSystem.java:529)
	at org.openide.filesystems.FileObject.dispatchEvent(FileObject.java:619)
	at org.openide.filesystems.FileObject.fireFileDataCreatedEvent(FileObject.java:571)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.fireFileDataCreatedEvent(BaseFileObj.java:648)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.refreshImpl(FolderObj.java:483)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.refresh(BaseFileObj.java:874)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.refresh(FolderObj.java:537)
	at org.openide.filesystems.FileObject.refresh(FileObject.java:1233)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectFactory.refreshFromGetter(FileObjectFactory.java:908)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectFactory.issueIfExist(FileObjectFactory.java:310)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectFactory.getFileObject(FileObjectFactory.java:207)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectFactory.getValidFileObject(FileObjectFactory.java:777)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.listenToAllRecursion(FileObjectKeeper.java:238)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.listenToAll(FileObjectKeeper.java:200)
[catch] at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.addRecursiveListener(FileObjectKeeper.java:82)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.addRecursiveListener(FolderObj.java:657)
	at com.jme3.gde.core.assets.ProjectAssetManager.loadClassLoader(ProjectAssetManager.java:180)
	at com.jme3.gde.core.assets.ProjectAssetManager$3.run(ProjectAssetManager.java:293)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.postRequest(DefaultMutexImplementation.java:964)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.postWriteRequest(DefaultMutexImplementation.java:292)
	at org.openide.util.Mutex.postWriteRequest(Mutex.java:369)
	at com.jme3.gde.core.assets.ProjectAssetManager.updateClassLoader(ProjectAssetManager.java:289)
	at com.jme3.gde.core.assets.ProjectAssetManager$1.fireChange(ProjectAssetManager.java:271)
	at com.jme3.gde.core.assets.ProjectAssetManager$1.fileChanged(ProjectAssetManager.java:256)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.fileChanged(FileObjectKeeper.java:342)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEventImpl(FCLSupport.java:153)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapperSingle.dispatchAllEventsSync(FCLSupport.java:199)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEvent(FCLSupport.java:112)
	at org.openide.filesystems.FCLSupport.dispatchEvent(FCLSupport.java:80)
	at org.openide.filesystems.FileObject$ED.dispatch(FileObject.java:1416)
	at org.openide.filesystems.FileSystem$EventDispatcher.run(FileSystem.java:770)
	at org.openide.filesystems.EventControl.dispatchEvent(EventControl.java:59)
	at org.openide.filesystems.FileSystem.dispatchEvent(FileSystem.java:529)
	at org.openide.filesystems.FileObject.dispatchEvent(FileObject.java:619)
	at org.openide.filesystems.FileObject.fireFileChangedEvent(FileObject.java:587)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.fireFileChangedEvent(BaseFileObj.java:699)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObj.refreshImpl(FileObj.java:344)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.refresh(BaseFileObj.java:874)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObj.refresh(FileObj.java:355)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.refreshImpl(FolderObj.java:459)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.refresh(BaseFileObj.java:874)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.refresh(FolderObj.java:537)
	at org.openide.filesystems.FileObject.refresh(FileObject.java:1233)
	at org.netbeans.modules.masterfs.watcher.Watcher$1.run(Watcher.java:415)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
INFO [org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj]: Cannot refresh file C:/Users/Toni/Documents/ToniArts/BasicGame2/build/classes
WARNING [org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper]
java.lang.AssertionError: Already listening to [C:\Users\Toni\Documents\ToniArts\BasicGame2\build\classes@15c79722:72b59398] now requested for C:\Users\Toni\Documents\ToniArts\BasicGame2\build\classes@15c79722:72b59398
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.listenToAll(FileObjectKeeper.java:198)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.addRecursiveListener(FileObjectKeeper.java:82)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.addRecursiveListener(FolderObj.java:657)
	at com.jme3.gde.core.assets.ProjectAssetManager.loadClassLoader(ProjectAssetManager.java:180)
	at com.jme3.gde.core.assets.ProjectAssetManager$3.run(ProjectAssetManager.java:293)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.postRequest(DefaultMutexImplementation.java:975)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.postWriteRequest(DefaultMutexImplementation.java:292)
	at org.openide.util.Mutex.postWriteRequest(Mutex.java:369)
	at com.jme3.gde.core.assets.ProjectAssetManager.updateClassLoader(ProjectAssetManager.java:289)
	at com.jme3.gde.core.assets.ProjectAssetManager$2.propertyChange(ProjectAssetManager.java:279)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at org.netbeans.api.java.classpath.ClassPath.firePropertyChange(ClassPath.java:691)
	at org.netbeans.api.java.classpath.ClassPath$RootsListener.processEvent(ClassPath.java:1436)
	at org.netbeans.api.java.classpath.ClassPath$RootsListener.fileDataCreated(ClassPath.java:1413)
	at org.openide.filesystems.FileChangeImpl.fileDataCreated(FileChangeImpl.java:140)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEventImpl(FCLSupport.java:147)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapperSingle.dispatchAllEventsSync(FCLSupport.java:199)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEvent(FCLSupport.java:112)
	at org.openide.filesystems.FCLSupport.dispatchEvent(FCLSupport.java:80)
	at org.openide.filesystems.FileObject$ED.dispatch(FileObject.java:1416)
	at org.openide.filesystems.FileSystem$EventDispatcher.run(FileSystem.java:770)
	at org.openide.filesystems.EventControl.dispatchEvent(EventControl.java:59)
	at org.openide.filesystems.FileSystem.dispatchEvent(FileSystem.java:529)
	at org.openide.filesystems.FileObject.dispatchEvent(FileObject.java:619)
	at org.openide.filesystems.FileObject.fireFileDataCreatedEvent(FileObject.java:571)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.fireFileDataCreatedEvent(BaseFileObj.java:648)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.refreshImpl(FolderObj.java:483)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.refresh(BaseFileObj.java:874)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.refresh(FolderObj.java:537)
	at org.openide.filesystems.FileObject.refresh(FileObject.java:1233)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectFactory.refreshFromGetter(FileObjectFactory.java:908)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectFactory.issueIfExist(FileObjectFactory.java:310)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectFactory.getFileObject(FileObjectFactory.java:207)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectFactory.getValidFileObject(FileObjectFactory.java:777)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.listenToAllRecursion(FileObjectKeeper.java:238)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.listenToAll(FileObjectKeeper.java:200)
[catch] at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.addRecursiveListener(FileObjectKeeper.java:82)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.addRecursiveListener(FolderObj.java:657)
	at com.jme3.gde.core.assets.ProjectAssetManager.loadClassLoader(ProjectAssetManager.java:180)
	at com.jme3.gde.core.assets.ProjectAssetManager$3.run(ProjectAssetManager.java:293)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.postRequest(DefaultMutexImplementation.java:964)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.postWriteRequest(DefaultMutexImplementation.java:292)
	at org.openide.util.Mutex.postWriteRequest(Mutex.java:369)
	at com.jme3.gde.core.assets.ProjectAssetManager.updateClassLoader(ProjectAssetManager.java:289)
	at com.jme3.gde.core.assets.ProjectAssetManager$1.fireChange(ProjectAssetManager.java:271)
	at com.jme3.gde.core.assets.ProjectAssetManager$1.fileChanged(ProjectAssetManager.java:256)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.fileChanged(FileObjectKeeper.java:342)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEventImpl(FCLSupport.java:153)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapperSingle.dispatchAllEventsSync(FCLSupport.java:199)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEvent(FCLSupport.java:112)
	at org.openide.filesystems.FCLSupport.dispatchEvent(FCLSupport.java:80)
	at org.openide.filesystems.FileObject$ED.dispatch(FileObject.java:1416)
	at org.openide.filesystems.FileSystem$EventDispatcher.run(FileSystem.java:770)
	at org.openide.filesystems.EventControl.dispatchEvent(EventControl.java:59)
	at org.openide.filesystems.FileSystem.dispatchEvent(FileSystem.java:529)
	at org.openide.filesystems.FileObject.dispatchEvent(FileObject.java:619)
	at org.openide.filesystems.FileObject.fireFileChangedEvent(FileObject.java:587)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.fireFileChangedEvent(BaseFileObj.java:699)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObj.refreshImpl(FileObj.java:344)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.refresh(BaseFileObj.java:874)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObj.refresh(FileObj.java:355)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.refreshImpl(FolderObj.java:459)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.refresh(BaseFileObj.java:874)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.refresh(FolderObj.java:537)
	at org.openide.filesystems.FileObject.refresh(FileObject.java:1233)
	at org.netbeans.modules.masterfs.watcher.Watcher$1.run(Watcher.java:415)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
INFO [org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj]: Cannot refresh file C:/Users/Toni/Documents/ToniArts/BasicGame2/build/classes/mygame/Main.class
INFO [org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj]: Cannot refresh file C:/Users/Toni/Documents/ToniArts/BasicGame2/build/classes/mygame
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.netbeans.modules.masterfs.watcher.Watcher$1
java.lang.AssertionError: Already listening to [C:\Users\Toni\Documents\ToniArts\BasicGame2\build\classes@15c79722:72b59398] now requested for C:\Users\Toni\Documents\ToniArts\BasicGame2\build\classes@15c79722:72b59398
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.listenToAll(FileObjectKeeper.java:198)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.addRecursiveListener(FileObjectKeeper.java:82)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.addRecursiveListener(FolderObj.java:657)
	at com.jme3.gde.core.assets.ProjectAssetManager.loadClassLoader(ProjectAssetManager.java:180)
	at com.jme3.gde.core.assets.ProjectAssetManager$3.run(ProjectAssetManager.java:293)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.postRequest(DefaultMutexImplementation.java:975)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.postWriteRequest(DefaultMutexImplementation.java:292)
	at org.openide.util.Mutex.postWriteRequest(Mutex.java:369)
	at com.jme3.gde.core.assets.ProjectAssetManager.updateClassLoader(ProjectAssetManager.java:289)
	at com.jme3.gde.core.assets.ProjectAssetManager$2.propertyChange(ProjectAssetManager.java:279)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at org.netbeans.api.java.classpath.ClassPath.firePropertyChange(ClassPath.java:691)
	at org.netbeans.api.java.classpath.ClassPath$RootsListener.processEvent(ClassPath.java:1436)
	at org.netbeans.api.java.classpath.ClassPath$RootsListener.fileDataCreated(ClassPath.java:1413)
	at org.openide.filesystems.FileChangeImpl.fileDataCreated(FileChangeImpl.java:140)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEventImpl(FCLSupport.java:147)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapperSingle.dispatchAllEventsSync(FCLSupport.java:199)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEvent(FCLSupport.java:112)
	at org.openide.filesystems.FCLSupport.dispatchEvent(FCLSupport.java:80)
	at org.openide.filesystems.FileObject$ED.dispatch(FileObject.java:1416)
	at org.openide.filesystems.FileSystem$EventDispatcher.run(FileSystem.java:770)
	at org.openide.filesystems.EventControl.dispatchEvent(EventControl.java:59)
	at org.openide.filesystems.FileSystem.dispatchEvent(FileSystem.java:529)
	at org.openide.filesystems.FileObject.dispatchEvent(FileObject.java:619)
	at org.openide.filesystems.FileObject.fireFileDataCreatedEvent(FileObject.java:571)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.fireFileDataCreatedEvent(BaseFileObj.java:648)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.refreshImpl(FolderObj.java:483)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.refresh(BaseFileObj.java:874)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.refresh(FolderObj.java:537)
	at org.openide.filesystems.FileObject.refresh(FileObject.java:1233)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectFactory.refreshFromGetter(FileObjectFactory.java:908)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectFactory.issueIfExist(FileObjectFactory.java:310)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectFactory.getFileObject(FileObjectFactory.java:207)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectFactory.getValidFileObject(FileObjectFactory.java:777)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.listenToAllRecursion(FileObjectKeeper.java:238)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.listenToAll(FileObjectKeeper.java:200)
[catch] at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.addRecursiveListener(FileObjectKeeper.java:82)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.addRecursiveListener(FolderObj.java:657)
	at com.jme3.gde.core.assets.ProjectAssetManager.loadClassLoader(ProjectAssetManager.java:180)
	at com.jme3.gde.core.assets.ProjectAssetManager$3.run(ProjectAssetManager.java:293)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.postRequest(DefaultMutexImplementation.java:964)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.postWriteRequest(DefaultMutexImplementation.java:292)
	at org.openide.util.Mutex.postWriteRequest(Mutex.java:369)
	at com.jme3.gde.core.assets.ProjectAssetManager.updateClassLoader(ProjectAssetManager.java:289)
	at com.jme3.gde.core.assets.ProjectAssetManager$1.fireChange(ProjectAssetManager.java:271)
	at com.jme3.gde.core.assets.ProjectAssetManager$1.fileChanged(ProjectAssetManager.java:256)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObjectKeeper.fileChanged(FileObjectKeeper.java:342)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEventImpl(FCLSupport.java:153)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapperSingle.dispatchAllEventsSync(FCLSupport.java:199)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEvent(FCLSupport.java:112)
	at org.openide.filesystems.FCLSupport.dispatchEvent(FCLSupport.java:80)
	at org.openide.filesystems.FileObject$ED.dispatch(FileObject.java:1416)
	at org.openide.filesystems.FileSystem$EventDispatcher.run(FileSystem.java:770)
	at org.openide.filesystems.EventControl.dispatchEvent(EventControl.java:59)
	at org.openide.filesystems.FileSystem.dispatchEvent(FileSystem.java:529)
	at org.openide.filesystems.FileObject.dispatchEvent(FileObject.java:619)
	at org.openide.filesystems.FileObject.fireFileChangedEvent(FileObject.java:587)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.fireFileChangedEvent(BaseFileObj.java:699)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObj.refreshImpl(FileObj.java:344)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.refresh(BaseFileObj.java:874)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObj.refresh(FileObj.java:355)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.refreshImpl(FolderObj.java:459)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.refresh(BaseFileObj.java:874)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.refresh(FolderObj.java:537)
	at org.openide.filesystems.FileObject.refresh(FileObject.java:1233)
	at org.netbeans.modules.masterfs.watcher.Watcher$1.run(Watcher.java:415)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused: org.openide.util.RequestProcessor$SlowItem
	at org.openide.util.RequestProcessor$Task.schedule(RequestProcessor.java:1459)
	at org.netbeans.modules.masterfs.watcher.Watcher.enqueue(Watcher.java:428)
	at org.netbeans.modules.masterfs.watcher.Watcher.access$300(Watcher.java:55)
	at org.netbeans.modules.masterfs.watcher.Watcher$Ext.run(Watcher.java:347)
[catch] at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by neph1** [comment]
Although there is no reference to it in the stacktrace, I guess it's related to ExternalChangeScanner? Are there other instances listening for asset changes? I made some changes to it last spring, when working on the new animation controls, and a small thing again a couple of months ago when allowing it to "remember the selected option".
