### ISSUE TITLE
Exception when creating ParticleEmitter

### ISSUE THREAD

**Issue by neph1** [jMonkeyEngine/sdk#479]
Steps:
1. Create new scene in SceneComposer
2. Right click on Root Node and create new Spatial -> ParticleEmitter

The scene displays the default particle emitter, but SceneExplorer is empty and the following exception is shown:

```
java.lang.NoClassDefFoundError: Could not initialize class com.jme3.gde.core.sceneexplorer.nodes.JmeParticleEmitter
    at com.jme3.gde.core.sceneexplorer.nodes.JmeSpatialChildren.createNodes(JmeSpatialChildren.java:202)
    at org.openide.nodes.Children$Keys$KE.nodes(Children.java:1654)
    at org.openide.nodes.ChildrenArray.nodesFor(ChildrenArray.java:124)
    at org.openide.nodes.EntrySupportDefault$Info.nodes(EntrySupportDefault.java:782)
    at org.openide.nodes.EntrySupportDefault.updateAdd(EntrySupportDefault.java:418)
    at org.openide.nodes.EntrySupportDefault.setEntries(EntrySupportDefault.java:272)
    at org.openide.nodes.EntrySupport.setEntries(EntrySupport.java:60)
    at org.openide.nodes.Children$Keys$2.run(Children.java:1548)
    at org.netbeans.modules.openide.util.DefaultMutexImplementation$1Exec.run(DefaultMutexImplementation.java:952)
    at org.openide.nodes.Children$ProjectManagerDeadlockDetector.execute(Children.java:1914)
    at org.netbeans.modules.openide.util.DefaultMutexImplementation.postRequest(DefaultMutexImplementation.java:958)
    at org.netbeans.modules.openide.util.DefaultMutexImplementation.postRequest(DefaultMutexImplementation.java:921)
    at org.netbeans.modules.openide.util.DefaultMutexImplementation.postWriteRequest(DefaultMutexImplementation.java:292)
    at org.openide.util.Mutex.postWriteRequest(Mutex.java:369)
    at org.openide.nodes.Children$Keys.applyKeys(Children.java:1557)
    at org.openide.nodes.Children$Keys.setKeys(Children.java:1501)
    at com.jme3.gde.core.sceneexplorer.nodes.JmeSpatialChildren.refreshChildren(JmeSpatialChildren.java:83)
    at com.jme3.gde.core.sceneexplorer.nodes.AbstractSceneExplorerNode.refresh(AbstractSceneExplorerNode.java:140)
    at com.jme3.gde.core.sceneexplorer.nodes.actions.NewSpatialPopup$2.run(NewSpatialPopup.java:208)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by neph1** [comment]
Wrong name for svg icon. Will fix
