### ISSUE TITLE
jMonkeyEngine 3.6.0 crashes on startup

### ISSUE THREAD

**Issue by forenbuddy** [jMonkeyEngine/sdk#494]
When I dare to start the jMonkEyengine 3.6 I receive

`java.lang.IllegalStateException: Missing hosting module org.netbeans.libs.javacimpl for fragment org.netbeans.modules.nbjavac.impl
	at org.netbeans.ModuleManager.refineClassLoader(ModuleManager.java:909)
	at org.netbeans.StandardModule.classLoaderUp(StandardModule.java:527)
	at org.netbeans.ModuleManager.doEnable(ModuleManager.java:1361)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1331)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1256)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:316)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:252)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:298)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:173)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:142)
	at org.netbeans.core.startup.Main.start(Main.java:303)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

and the death of the JmonkeyEngine instance right there.

Please fix or tell or hint me how to fix it!

I am on Debian Mate and willing to try out stuff.

**Comment by neph1** [comment]
Do you have a previous version of the SDK installed?

**Comment by tonihele** [comment]
I'm fairly sure this is about having left over settings from some old release. Delete the settings and that should be it. Closing this. Feel free to reopen if the problem persists.

**Comment by forenbuddy** [comment]
I found that thread also but it does not help me with jMonkey. Which settings would I delete then in/for jMonkey?

**Comment by neph1** [comment]
```
find the '.jmonkeyplatform' folder (usually in your 'home' directory).
Rename it to keep the configs.
Install.
Copy the 'config' folder from the renamed folder into the new '.jmonkeyplatform' folder.
```
