### ISSUE TITLE
Running Physics with Mixamo model without physics yields error

### ISSUE THREAD

**Issue by neph1** [jMonkeyEngine/sdk#536]
java.lang.AbstractMethodError: Receiver class com.jme3.bullet.BulletAppState does not define or inherit an implementation of the resolved method 'abstract java.lang.String getId()' of interface com.jme3.app.state.AppState.
    at com.jme3.app.state.AppStateManager.attach(AppStateManager.java:141)
    at com.jme3.gde.core.scene.SceneApplication$11.call(SceneApplication.java:689)
    at com.jme3.app.AppTask.invoke(AppTask.java:147)
    at com.jme3.app.LegacyApplication.runQueuedTasks(LegacyApplication.java:759)
    at com.jme3.app.LegacyApplication.update(LegacyApplication.java:775)
    at com.jme3.gde.core.scene.SceneApplication.update(SceneApplication.java:296)
    at com.jme3.system.awt.AwtPanelsContext.updateInThread(AwtPanelsContext.java:237)
    at com.jme3.system.awt.AwtPanelsContext.access$200(AwtPanelsContext.java:46)
    at com.jme3.system.awt.AwtPanelsContext$AwtPanelsListener.update(AwtPanelsContext.java:80)
    at com.jme3.system.lwjgl.LwjglOffscreenBuffer.runLoop(LwjglOffscreenBuffer.java:126)
    at com.jme3.system.lwjgl.LwjglOffscreenBuffer.run(LwjglOffscreenBuffer.java:160)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by neph1** [comment]
Not a quick fix, but should be solved by https://github.com/jMonkeyEngine/sdk/pull/547
