### ISSUE TITLE
SDK xbuf importer needs to be updated

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/sdk#90]
Hi 
Xbuf updated to Protobuf-3.0.0. SDK's Xbuf library needs to be updated too. Right now  trying to convert .xbuf in SDK which is exported with blender_io_xbuf v9.1 gives this exception : 
```

com.jme3.asset.AssetLoadException: An exception has occured while loading asset: Scenes/MagoTribe/MagoTribeMetaData.xbuf
    at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:261)
    at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
    at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
    at com.jme3.gde.core.assets.SpatialAssetDataObject.loadAsset(SpatialAssetDataObject.java:94)
    at com.jme3.gde.core.assets.actions.ConvertModel$1.run(ConvertModel.java:59)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: tobjects[0].transform.rotation.x, tobjects[0].transform.rotation.y, tobjects[0].transform.rotation.z, tobjects[1].transform.translation.y, tobjects[1].transform.rotation.x, tobjects[1].transform.rotation.y, tobjects[1].transform.rotation.z, tobjects[2].transform.translation.y, tobjects[2].transform.rotation.x, tobjects[2].transform.rotation.y, tobjects[2].transform.rotation.z, tobjects[3].transform.translation.y, tobjects[3].transform.rotation.x, tobjects[3].transform.rotation.y, tobjects[3].transform.rotation.z, tobjects[4].transform.translation.y, tobjects[4].transform.rotation.x, tobjects[4].transform.rotation.y, tobjects[4].transform.rotation.z, tobjects[5].transform.translation.y, tobjects[5].transform.rotation.x, tobjects[5].transform.rotation.y, tobjects[5].transform.rotation.z, tobjects[6].transform.translation.y, tobjects[6].transform.rotation.x, tobjects[6].transform.rotation.y, tobjects[6].transform.rotation.z, tobjects[7].transform.translation.y, tobjects[7].transform.rotation.x, tobjects[7].transform.rotation.y, tobjects[7].transform.rotation.z, tobjects[8].transform.translation.y, tobjects[8].transform.rotation.x, tobjects[8].transform.rotation.y, tobjects[8].transform.rotation.z, tobjects[9].transform.translation.y, tobjects[9].transform.rotation.x, tobjects[9].transform.rotation.y, tobjects[9].transform.rotation.z, tobjects[10].transform.translation.y, tobjects[10].transform.rotation.x, tobjects[10].transform.rotation.y, tobjects[10].transform.rotation.z, tobjects[11].transform.translation.y, tobjects[11].transform.rotation.x, tobjects[11].transform.rotation.y, tobjects[11].transform.rotation.z, tobjects[12].transform.translation.y, tobjects[12].transform.rotation.x, tobjects[12].transform.rotation.y, tobjects[12].transform.rotation.z, tobjects[13].transform.rotation.x, tobjects[13].transform.rotation.y, tobjects[13].transform.rotation.z, tobjects[14].transform.translation.y, tobjects[14].transform.rotation.x, tobjects[14].transform.rotation.y, tobjects[14].transform.rotation.z, tobjects[15].transform.translation.y, tobjects[15].transform.rotation.x, tobjects[15].transform.rotation.y, tobjects[15].transform.rotation.z, tobjects[16].transform.rotation.x, tobjects[16].transform.rotation.z, meshes[0].vertexArrays[1].attrib
    at com.google.protobuf.UninitializedMessageException.asInvalidProtocolBufferException(UninitializedMessageException.java:81)
    at com.google.protobuf.AbstractParser.checkMessageInitialized(AbstractParser.java:71)
    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
    at xbuf.Datas$Data.parseFrom(Datas.java:1082)
    at jme3_ext_xbuf.XbufLoader.load(XbufLoader.java:35)
    at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
    ... 5 more



```
Thanks

**Comment by grizeldi** [comment]
@MeFisto94 Is this just a matter of changing the version number in build.gradle or is there anything else to be done?

**Comment by MeFisto94** [comment]
You also have to release a new sdk release, which I'll do as soon as I have some feedback about our iOS Improvements.

The reason for waiting is that we currently have so many useless releases (3.1-alpha4-SNAPSHOT), which seem to confuse users.
Especially: How do you order those: { 3.1-beta1-unstable-SNAPSHOT, 3.1-beta1-xbuf, 3.1-beta1-iOS }. 

You can only do this by looking at the order and how many commits have been made since.

**Comment by empirephoenix** [comment]
How about using a simpler scheme then?

3.1.x-SNAPSHOT and just increment x each time, at least they have a clear order then.

**Comment by MeFisto94** [comment]
Then it doesn't comply with the engine scheme of `3.1-beta1-SNAPSHOT`. I'd rather do something like `3.1-beta1-SNAPSHOT-001` but that's all a bit overkill.

If the engine would start it's release cycle again I wouldn't have to release multiple beta1 versions actually

**Comment by Ali-RS** [comment]
this commit updated dependency :  https://github.com/jMonkeyEngine/sdk/commit/c86f6883540bd4e439b8ac2b5a85d48d436b0900

thanks
