### ISSUE TITLE
A lot of crashes in JME3 test examples project

### ISSUE THREAD

**Issue by nordfalk** [jMonkeyEngine/sdk#96]
Ive tried to running ALL the examples and noted down the crashes. As you can see there are really many which fails, which makes it hard for a beginner to get started.
So please fix the majority of these errors ;-)

I'm using the 3.1-beta1-b002-SNAPSHOT(on Ubuntu 16). I experienced a simillar frequency of errors when running on the earlier 3.1-beta snapshot.

In startApp() in TestChooser.java I added
```
                    java.util.logging.Logger.getLogger("").setLevel(Level.SEVERE);

                    for (int i = 0; i < appClass.length; i++) {
                	    Class<?> clazz = (Class)appClass[i];
                                System.err.println("");
                                System.out.println("INVOKING "+clazz);
                                System.err.println("");
                		try {
```

to and then I selected all the tests.

Here below is stack traces for most of the tests that failed:

You need to correct URL  http://jmonkeyengine.googlecode.com/files/wildhouse.zip in

INVOKING class jme3test.post.TestPostFiltersCompositing
INVOKING class jme3test.post.TestFog
INVOKING class jme3test.scene.TestSceneLoading

```
WARNING: Failed to set root path http://jmonkeyengine.googlecode.com/files/wildhouse.zip
java.io.IOException: 404 Not Found
	at com.jme3.asset.plugins.HttpZipLocator.readData(HttpZipLocator.java:196)
	at com.jme3.asset.plugins.HttpZipLocator.readEndHeader(HttpZipLocator.java:295)
	at com.jme3.asset.plugins.HttpZipLocator.load(HttpZipLocator.java:322)
	at com.jme3.asset.plugins.HttpZipLocator.setRootPath(HttpZipLocator.java:346)
	at com.jme3.asset.ImplHandler$ImplThreadLocal.initialValue(ImplHandler.java:119)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at com.jme3.asset.ImplHandler.tryLocate(ImplHandler.java:177)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:359)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:420)
	at jme3test.post.TestPostFiltersCompositing.makeScene(TestPostFiltersCompositing.java:106)
	at jme3test.post.TestPostFiltersCompositing.simpleInitApp(TestPostFiltersCompositing.java:71)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:745)

sep. 20, 2016 9:47:43 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,6,main]
java.lang.NullPointerException
	at com.jme3.asset.plugins.HttpZipLocator.locate(HttpZipLocator.java:354)
	at com.jme3.asset.ImplHandler.tryLocate(ImplHandler.java:177)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:359)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:420)
	at jme3test.post.TestPostFiltersCompositing.makeScene(TestPostFiltersCompositing.java:106)
	at jme3test.post.TestPostFiltersCompositing.simpleInitApp(TestPostFiltersCompositing.java:71)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:745)
```

INVOKING class jme3test.asset.TestUrlLoading

```
SEVERE: Uncaught exception thrown in Thread[jME3 Main,6,main]
com.jme3.asset.AssetNotFoundException: mucha-window.png (Mipmapped)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:370)
	at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:390)
	at jme3test.asset.TestUrlLoading.simpleInitApp(TestUrlLoading.java:67)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:745)
```

INVOKING class jme3test.asset.TestCustomLoader
INVOKING class me3test.asset.TestOnlineJar

```
SEVERE: main() method had exception: jme3test.asset.TestManyLocators
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jme3test.TestChooser$2.run(TestChooser.java:288)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.jme3.asset.AssetLoadException: Failed to open zip file: town.zip
	at com.jme3.asset.plugins.ZipLocator.setRootPath(ZipLocator.java:79)
	at com.jme3.asset.ImplHandler$ImplThreadLocal.initialValue(ImplHandler.java:119)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at com.jme3.asset.ImplHandler.tryLocate(ImplHandler.java:177)
	at com.jme3.asset.DesktopAssetManager.locateAsset(DesktopAssetManager.java:191)
	at jme3test.asset.TestManyLocators.main(TestManyLocators.java:59)
	... 6 more
Caused by: java.io.FileNotFoundException: town.zip (Ingen sådan fil eller filkatalog)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at com.jme3.asset.plugins.ZipLocator.setRootPath(ZipLocator.java:77)
	... 12 more
```

INVOKING class jme3test.niftygui.TestNiftyExamples
INVOKING class jme3test.niftygui.TestNiftyToMesh

```
java.lang.RuntimeException: com.jme3.asset.AssetNotFoundException: all/intro.xml
	at de.lessvoid.nifty.Nifty.loadFromFile(Nifty.java:663)
	at de.lessvoid.nifty.Nifty.fromXml(Nifty.java:520)
	at jme3test.niftygui.TestNiftyExamples.simpleInitApp(TestNiftyExamples.java:56)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.jme3.asset.AssetNotFoundException: all/intro.xml
	at com.jme3.niftygui.NiftyJmeDisplay$ResourceLocationJme.getResourceAsStream(NiftyJmeDisplay.java:83)
	at de.lessvoid.nifty.tools.resourceloader.NiftyResourceLoader.getResourceAsStream(NiftyResourceLoader.java:69)
	at de.lessvoid.nifty.Nifty.getResourceAsStream(Nifty.java:2013)
	at de.lessvoid.nifty.Nifty.loadFromFile(Nifty.java:651)
	... 6 more
```

INVOKING class jme3test.renderer.TestInconsistentCompareDetection

```
sep. 20, 2016 10:55:21 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,6,main]
java.lang.UnsupportedOperationException: Compare function result changed! Make sure you do not modify the scene from another thread!
	at com.jme3.util.ListSort.mergeLow(ListSort.java:702)
	at com.jme3.util.ListSort.mergeRuns(ListSort.java:474)
	at com.jme3.util.ListSort.mergeCollapse(ListSort.java:407)
	at com.jme3.util.ListSort.sort(ListSort.java:233)
	at com.jme3.renderer.queue.GeometryList.sort(GeometryList.java:158)
	at com.jme3.renderer.queue.RenderQueue.renderGeometryList(RenderQueue.java:262)
	at com.jme3.renderer.queue.RenderQueue.renderQueue(RenderQueue.java:305)
	at com.jme3.renderer.RenderManager.renderViewPortQueues(RenderManager.java:870)
	at com.jme3.renderer.RenderManager.flushQueue(RenderManager.java:781)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1097)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1145)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:253)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:745)
```

INVOKING class jme3test.material.TestColoredTexture

```
sep. 20, 2016 11:13:46 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,6,main]
com.jme3.asset.AssetLoadException: This material definition is deprecated. Please use Unshaded.j3md instead.
	at com.jme3.material.plugins.J3MLoader.loadFromRoot(J3MLoader.java:669)
	at com.jme3.material.plugins.J3MLoader.load(J3MLoader.java:757)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at com.jme3.material.Material.<init>(Material.java:106)
	at jme3test.material.TestColoredTexture.simpleInitApp(TestColoredTexture.java:60)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:745)
```

INVOKING class jme3test.stress.TestParallelTangentGeneration

```
sep. 20, 2016 11:17:04 PM com.jme3.util.TangentBinormalGenerator processTriangleData
WARNING: Angle between tangents exceeds tolerance for vertex 1.
sep. 20, 2016 11:17:04 PM com.jme3.util.TangentBinormalGenerator processTriangleData
WARNING: Angle between tangents exceeds tolerance for vertex 2.
sep. 20, 2016 11:17:04 PM com.jme3.util.TangentBinormalGenerator processTriangleData
WARNING: Angle between tangents exceeds tolerance for vertex 3.
sep. 20, 2016 11:17:04 PM com.jme3.util.TangentBinormalGenerator processTriangleData
WARNING: Angle between tangents exceeds tolerance for vertex 6.
sep. 20, 2016 11:17:04 PM com.jme3.util.TangentBinormalGenerator processTriangleData
WARNING: Angle between tangents exceeds tolerance for vertex 7.

```

INVOKING class jme3test.blender.TestBlenderLoader

```
sep. 20, 2016 11:18:28 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
sep. 20, 2016 11:18:28 PM com.jme3.scene.plugins.blender.file.FileBlockHeader$BlockCode valueOf
WARNING: Unknown block header: PY00
sep. 20, 2016 11:18:28 PM com.jme3.scene.plugins.blender.file.FileBlockHeader$BlockCode valueOf
WARNING: Unknown block header: PY00
sep. 20, 2016 11:18:28 PM com.jme3.scene.plugins.blender.file.FileBlockHeader$BlockCode valueOf
WARNING: Unknown block header: PY00
sep. 20, 2016 11:18:29 PM com.jme3.scene.plugins.blender.meshes.Face triangulate
WARNING: Errors occured during face triangulation: Unable to find two closest vertices while triangulating face in mesh: TemporalMesh [name=Cone.008, vertices.size()=336]Please apply triangulation modifier in blender as a workaround and load again!. The face will be triangulated with the most direct algorithm, but the results might not be identical to blender.
sep. 20, 2016 11:18:29 PM com.jme3.scene.plugins.blender.meshes.Face triangulate
WARNING: Errors occured during face triangulation: Unable to find two closest vertices while triangulating face in mesh: TemporalMesh [name=Cone.008, vertices.size()=336]Please apply triangulation modifier in blender as a workaround and load again!. The face will be triangulated with the most direct algorithm, but the results might not be identical to blender.
sep. 20, 2016 11:18:29 PM com.jme3.scene.plugins.blender.meshes.Face triangulate
WARNING: Errors occured during face triangulation: Unable to find two closest vertices while triangulating face in mesh: TemporalMesh [name=Cone.008, vertices.size()=336]Please apply triangulation modifier in blender as a workaround and load again!. The face will be triangulated with the most direct algorithm, but the results might not be identical to blender.
sep. 20, 2016 11:18:29 PM com.jme3.scene.plugins.blender.meshes.Face triangulate
WARNING: Errors occured during face triangulation: Unable to find two closest vertices while triangulating face in mesh: TemporalMesh [name=Cone.008, vertices.size()=336]Please apply triangulation modifier in blender as a workaround and load again!. The face will be triangulated with the most direct algorithm, but the results might not be identical to blender.
sep. 20, 2016 11:18:29 PM com.jme3.scene.plugins.blender.meshes.Face triangulate
WARNING: Errors occured during face triangulation: Unable to find two closest vertices while triangulating face in mesh: TemporalMesh [name=Cone.008, vertices.size()=336]Please apply triangulation modifier in blender as a workaround and load again!. The face will be triangulated with the most direct algorithm, but the results might not be identical to blender.
sep. 20, 2016 11:18:29 PM com.jme3.scene.plugins.blender.meshes.Face triangulate
WARNING: Errors occured during face triangulation: Unable to find two closest vertices while triangulating face in mesh: TemporalMesh [name=Cone.008, vertices.size()=336]Please apply triangulation modifier in blender as a workaround and load again!. The face will be triangulated with the most direct algorithm, but the results might not be identical to blender.
sep. 20, 2016 11:18:29 PM com.jme3.scene.plugins.blender.meshes.Face triangulate

```

INVOKING class jme3test.terrain.TerrainGridAlphaMapTest

```
sep. 20, 2016 11:19:36 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
sep. 20, 2016 11:19:36 PM com.jme3.material.plugins.J3MLoader readDefine
WARNING: In technique 'GBuf':
Define 'VERTEX_COLOR' mapped to non-existent material parameter 'UseVertexColor', ignoring.
sep. 20, 2016 11:19:36 PM com.jme3.material.plugins.J3MLoader readDefine
WARNING: In technique 'GBuf':
Define 'MATERIAL_COLORS' mapped to non-existent material parameter 'UseMaterialColors', ignoring.
sep. 20, 2016 11:19:36 PM com.jme3.material.plugins.J3MLoader readDefine
WARNING: In technique 'GBuf':
Define 'V_TANGENT' mapped to non-existent material parameter 'VTangent', ignoring.
sep. 20, 2016 11:19:36 PM com.jme3.material.plugins.J3MLoader readDefine
WARNING: In technique 'GBuf':
Define 'MINNAERT' mapped to non-existent material parameter 'Minnaert', ignoring.
sep. 20, 2016 11:19:36 PM com.jme3.material.plugins.J3MLoader readDefine
WARNING: In technique 'GBuf':
Define 'PARALLAXMAP' mapped to non-existent material parameter 'ParallaxMap', ignoring.
sep. 20, 2016 11:19:36 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,6,main]
java.lang.NoClassDefFoundError: com/bulletphysics/collision/dispatch/CollisionWorld$RayResultCallback
	at com.jme3.bullet.BulletAppState.startPhysics(BulletAppState.java:164)
	at com.jme3.bullet.BulletAppState.stateAttached(BulletAppState.java:211)
	at com.jme3.app.state.AppStateManager.attach(AppStateManager.java:133)
	at jme3test.terrain.TerrainGridAlphaMapTest.simpleInitApp(TerrainGridAlphaMapTest.java:164)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.bulletphysics.collision.dispatch.CollisionWorld$RayResultCallback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
```

INVOKING class jme3test.terrain.TerrainGridSerializationTest

```
sep. 20, 2016 11:21:07 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
sep. 20, 2016 11:21:07 PM com.jme3.material.plugins.J3MLoader readTechnique
WARNING: Fixed function technique was ignored
sep. 20, 2016 11:21:07 PM com.jme3.material.plugins.J3MLoader readTechnique
WARNING: Fixed function technique 'Default' was ignored for material Common/MatDefs/Terrain/HeightBasedTerrain.j3md
sep. 20, 2016 11:21:07 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,6,main]
java.lang.IllegalArgumentException
	at java.util.concurrent.ConcurrentLinkedQueue.addAll(ConcurrentLinkedQueue.java:520)
	at com.jme3.scene.control.UpdateControl.jmeClone(UpdateControl.java:107)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:249)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.util.clone.ListCloneFunction.cloneFields(ListCloneFunction.java:66)
	at com.jme3.util.clone.ListCloneFunction.cloneFields(ListCloneFunction.java:43)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:228)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.scene.Spatial.cloneFields(Spatial.java:1505)
	at com.jme3.scene.Node.cloneFields(Node.java:723)
	at com.jme3.terrain.geomipmap.TerrainQuad.cloneFields(TerrainQuad.java:1801)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:255)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:160)
	at com.jme3.scene.Spatial.clone(Spatial.java:1360)
	at com.jme3.scene.Node.clone(Node.java:682)
	at com.jme3.terrain.geomipmap.TerrainQuad.clone(TerrainQuad.java:1768)
	at com.jme3.terrain.geomipmap.TerrainQuad.clone(TerrainQuad.java:1763)
	at com.jme3.terrain.geomipmap.TerrainQuad.clone(TerrainQuad.java:109)
	at com.jme3.asset.CloneableAssetProcessor.createClone(CloneableAssetProcessor.java:48)
	at com.jme3.asset.DesktopAssetManager.registerAndCloneSmartAsset(DesktopAssetManager.java:317)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:379)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:420)
	at jme3test.terrain.TerrainGridSerializationTest.simpleInitApp(TerrainGridSerializationTest.java:50)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:745)
```

INVOKING class jme3test.terrain.TerrainGridTest

```
sep. 20, 2016 11:21:52 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
sep. 20, 2016 11:21:52 PM com.jme3.material.plugins.J3MLoader readTechnique
WARNING: Fixed function technique was ignored
sep. 20, 2016 11:21:52 PM com.jme3.material.plugins.J3MLoader readTechnique
WARNING: Fixed function technique 'Default' was ignored for material Common/MatDefs/Terrain/HeightBasedTerrain.j3md
sep. 20, 2016 11:21:52 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,6,main]
java.lang.NoClassDefFoundError: com/bulletphysics/collision/dispatch/CollisionWorld$RayResultCallback
	at com.jme3.bullet.BulletAppState.startPhysics(BulletAppState.java:164)
	at com.jme3.bullet.BulletAppState.stateAttached(BulletAppState.java:211)
	at com.jme3.app.state.AppStateManager.attach(AppStateManager.java:133)
	at jme3test.terrain.TerrainGridTest.simpleInitApp(TerrainGridTest.java:116)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.bulletphysics.collision.dispatch.CollisionWorld$RayResultCallback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
```

INVOKING class jme3test.terrain.TerrainGridTileLoaderTest
INVOKING class jme3test.batching.TestBatchNodeTower
INVOKING class jme3test.bullet.TestBoneRagdoll
NVOKING class jme3test.bullet.TestBetterCharacter
INVOKING class jme3test.bullet.TestFancyCar
INVOKING class jme3test.bullet.TestQ3

```
sep. 20, 2016 11:22:41 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
sep. 20, 2016 11:22:41 PM com.jme3.material.plugins.J3MLoader readTechnique
WARNING: Fixed function technique was ignored
sep. 20, 2016 11:22:41 PM com.jme3.material.plugins.J3MLoader readTechnique
WARNING: Fixed function technique 'Default' was ignored for material Common/MatDefs/Terrain/HeightBasedTerrain.j3md
sep. 20, 2016 11:22:41 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,6,main]
java.lang.NoClassDefFoundError: com/bulletphysics/collision/dispatch/CollisionWorld$RayResultCallback
	at com.jme3.bullet.BulletAppState.startPhysics(BulletAppState.java:164)
	at com.jme3.bullet.BulletAppState.stateAttached(BulletAppState.java:211)
	at com.jme3.app.state.AppStateManager.attach(AppStateManager.java:133)
	at jme3test.terrain.TerrainGridTileLoaderTest.simpleInitApp(TerrainGridTileLoaderTest.java:120)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.bulletphysics.collision.dispatch.CollisionWorld$RayResultCallback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
```

INVOKING class jme3test.water.TestPostWaterLake
INVOKING class jme3test.water.TestSceneWater
        Spatial scene = assetManager.loadModel("main.scene"); fails

```
sep. 20, 2016 11:28:00 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,6,main]
java.lang.NullPointerException
	at com.jme3.asset.plugins.HttpZipLocator.locate(HttpZipLocator.java:354)
	at com.jme3.asset.ImplHandler.tryLocate(ImplHandler.java:177)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:359)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:420)
	at jme3test.water.TestPostWaterLake.simpleInitApp(TestPostWaterLake.java:79)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:745)
```

INVOKING class jme3test.model.anim.TestBlenderObjectAnim

```
sep. 20, 2016 11:35:59 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,6,main]
java.lang.NullPointerException
	at jme3test.model.anim.TestBlenderObjectAnim.simpleInitApp(TestBlenderObjectAnim.java:76)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:130)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by MeFisto94** [comment]
This is actually rather related to the engine guys.
The problem is, that I don't know if we have those assets stored somewhere else? Probably only in jme3-test-data? Or not at all since they used to be hosted at google code?
@normen ?

Unrelated to that TestBlenderObjectAnim crashes (but there is an issue for that on the engine repo iirc),

Some bullet issues: Try to see if the "jbullet.jar" is added to the project libraries. If not then it's a mis-setup of the sdk test template.

 jme3test.terrain.TerrainGridSerializationTest has some cloning issues, it seems, @pspeed42 
 jme3test.material.TestColoredTexture contains a deprecated Material Definition, @Nehon

**Comment by grizeldi** [comment]
jme3-test-data is part of current release I think so it must be stored somewhere.

**Comment by Ev1lbl0w** [comment]
I was able to fix most of the problems, except the ones on jme3test.model.anim.TestBlenderObjectAnim and jme3test.terrain.TerrainGridSerializationTest. Here is [the project](https://drive.google.com/file/d/0B_BhrQ2WujmxSDJUcnptbW9GbDA/view?usp=sharing). I mostly fixed dead links and missing libs (you must add all libs from the libs folder). I would make a pull request but I can't find the JmeTests template on the repo (the one on the root doesn't even have a src folder).

**Comment by Ali-RS** [comment]
> I can't find the JmeTests template on the repo
I think it is here https://github.com/jMonkeyEngine/jmonkeyengine/tree/master/jme3-examples

**Comment by Ev1lbl0w** [comment]
Thanks you @Ali-RS, I'll do a pull request later then.

**Comment by Ev1lbl0w** [comment]
**Alright, made the pull request. I was able to fix the following:**

_scene.TestSceneLoading
asset.TestUrlLoading
asset.TestOnlineJar
terrain.TerrainGridAlphaMapTest
terrain.TerrainGridTest
water.TestSceneWater
material.TestColoredTexture_

**This one is not a problem, it's intentional:**

_renderer.TestInconsistentCompareDetection_

** These ones were only printed to the console and didn't stop the example to launch, so I'll assume they're verbose**

_stress.TestParallelTangentGeneration
blender.TestBlenderLoader_

**These ones require you to add libs to the project:**

_**Add nifty-examples.jar lib**_

_niftygui.TestNiftyToMesh_

**_Add jbullet.jar lib_**

_terrain.TerrainGridAlphaMapTest
terrain.TerrainGridTest
bullet.TestQ3_

**These ones I couldn't find a way to fix:**

_terrain.TerrainGridSerializationTest
model.anim.TestBlenderObjectAnim_

**Comment by stephengold** [comment]
I ran through all the examples recently when I released v3.2.2 of the Engine.

The `TestBlenderObjectAnim` crash was Engine issue 240, which was fixed in v3.2.2 of the Engine. I tested it in 3.2.2-stable-sdk1 and it works there.

The `TerrainGridSerializationTest` crash is Engine issue 997, which is fixed in the Engine's `master` branch. The fix will probably appear in the JME 3.2.3 release. I'm thinking March 2019. At which time this issue can probably be closed.
